from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field


@dataclass
class TemplateField:
    key: str
    label: str
    field_type: str = "text"
    required: bool = True
    placeholder: str = ""
    options: List[str] = field(default_factory=list)
    default_value: str = ""


@dataclass
class ContractTemplate:
    id: str
    name: str
    description: str
    category_id: str
    subcategory_id: str
    fields: List[TemplateField]
    outline_sections: List[str]
    prompt_template: str
    law_references: List[str] = field(default_factory=list)


@dataclass
class ContractSubcategory:
    id: str
    name: str
    description: str
    icon: str
    template_ids: List[str]


@dataclass
class ContractCategory:
    id: str
    name: str
    description: str
    icon: str
    color: str
    subcategories: List[ContractSubcategory]


CONTRACT_CATEGORIES: List[ContractCategory] = [
    ContractCategory(
        id="civil",
        name="民事合同",
        description="买卖、租赁、借款、赠与等民事类合同",
        icon="ph-handshake",
        color="bg-blue-500",
        subcategories=[
            ContractSubcategory(
                id="civil_sale",
                name="买卖合同",
                description="商品、房屋、机动车、设备等买卖交易",
                icon="ph-shopping-cart",
                template_ids=["civil_sale_goods", "civil_sale_house", "civil_sale_vehicle", "civil_sale_equipment"],
            ),
            ContractSubcategory(
                id="civil_lease",
                name="租赁合同",
                description="房屋、车辆、设备、场地等租赁",
                icon="ph-key",
                template_ids=["civil_lease_house", "civil_lease_vehicle", "civil_lease_equipment", "civil_lease_venue"],
            ),
            ContractSubcategory(
                id="civil_loan",
                name="借款合同",
                description="民间借贷、银行借款",
                icon="ph-money",
                template_ids=["civil_loan_private", "civil_loan_bank"],
            ),
            ContractSubcategory(
                id="civil_gift",
                name="赠与合同",
                description="财产赠与、股权赠与",
                icon="ph-gift",
                template_ids=["civil_gift_property", "civil_gift_equity"],
            ),
        ],
    ),
    ContractCategory(
        id="commercial",
        name="商事合同",
        description="服务、承揽、建设工程、运输、仓储等商事合同",
        icon="ph-buildings",
        color="bg-indigo-500",
        subcategories=[
            ContractSubcategory(
                id="comm_service",
                name="服务合同",
                description="咨询、技术、物业、委托代理等服务",
                icon="ph-headset",
                template_ids=["comm_service_consulting", "comm_service_technical", "comm_service_property", "comm_service_agency"],
            ),
            ContractSubcategory(
                id="comm_processing",
                name="承揽合同",
                description="加工、定制、维修等承揽业务",
                icon="ph-wrench",
                template_ids=["comm_processing_machining", "comm_processing_custom", "comm_processing_repair"],
            ),
            ContractSubcategory(
                id="comm_construction",
                name="建设工程合同",
                description="工程施工、设计、监理",
                icon="ph-crane",
                template_ids=["comm_constr_build", "comm_constr_design", "comm_constr_supervise"],
            ),
            ContractSubcategory(
                id="comm_transport",
                name="运输合同",
                description="货物运输、旅客运输",
                icon="ph-truck",
                template_ids=["comm_transport_cargo", "comm_transport_passenger"],
            ),
            ContractSubcategory(
                id="comm_storage",
                name="仓储/保管合同",
                description="货物存储与保管服务",
                icon="ph-warehouse",
                template_ids=["comm_storage_custody"],
            ),
        ],
    ),
    ContractCategory(
        id="labor",
        name="劳动人事合同",
        description="劳动合同、劳务合同及人事协议",
        icon="ph-users",
        color="bg-teal-500",
        subcategories=[
            ContractSubcategory(
                id="labor_contract",
                name="劳动合同/劳务合同",
                description="全日制、非全日制、劳务派遣",
                icon="ph-identification-card",
                template_ids=["labor_fulltime", "labor_parttime", "labor_dispatch"],
            ),
            ContractSubcategory(
                id="labor_hr",
                name="人事协议类合同",
                description="保密竞业、解除劳动关系、期权激励",
                icon="ph-shield-check",
                template_ids=["labor_hr_noncompete", "labor_hr_termination", "labor_hr_option"],
            ),
        ],
    ),
    ContractCategory(
        id="ip",
        name="知识产权合同",
        description="许可转让、开发等知识产权合同",
        icon="ph-lightbulb",
        color="bg-purple-500",
        subcategories=[
            ContractSubcategory(
                id="ip_license",
                name="许可/转让合同",
                description="专利、商标、著作权、软件著作权",
                icon="ph-certificate",
                template_ids=["ip_patent_transfer", "ip_trademark_license", "ip_copyright_transfer", "ip_software_license"],
            ),
            ContractSubcategory(
                id="ip_dev",
                name="开发合同",
                description="委托软件开发",
                icon="ph-code",
                template_ids=["ip_software_dev"],
            ),
        ],
    ),
    ContractCategory(
        id="investment",
        name="投融资合同",
        description="股权投资、担保等投融资合同",
        icon="ph-chart-line-up",
        color="bg-amber-500",
        subcategories=[
            ContractSubcategory(
                id="invest_equity",
                name="股权/投资合同",
                description="增资扩股、股权转让、投资意向书、合伙协议",
                icon="ph-chart-pie",
                template_ids=["invest_capital_increase", "invest_equity_transfer", "invest_term_sheet", "invest_partnership"],
            ),
            ContractSubcategory(
                id="invest_guarantee",
                name="担保合同",
                description="保证担保",
                icon="ph-shield",
                template_ids=["invest_guarantee"],
            ),
        ],
    ),
    ContractCategory(
        id="other",
        name="其他常用合同",
        description="和解协议、授权委托、婚前财产、不当得利等",
        icon="ph-folder",
        color="bg-slate-500",
        subcategories=[
            ContractSubcategory(
                id="other_common",
                name="其他合同",
                description="和解协议、授权委托、婚前财产、不当得利返还",
                icon="ph-file-text",
                template_ids=["other_settlement", "other_authorization", "other_prenuptial", "other_unjust_enrichment"],
            ),
        ],
    ),
]


CONTRACT_TEMPLATES: Dict[str, ContractTemplate] = {
    "civil_sale_goods": ContractTemplate(
        id="civil_sale_goods",
        name="商品买卖合同",
        description="适用于普通商品交易，涵盖标的物、价款、交付、验收、质量保证等条款",
        category_id="civil",
        subcategory_id="civil_sale",
        fields=[
            TemplateField(key="party_a", label="卖方（甲方）", placeholder="卖方名称/姓名", required=True),
            TemplateField(key="party_b", label="买方（乙方）", placeholder="买方名称/姓名", required=True),
            TemplateField(key="goods_name", label="商品名称", placeholder="如：笔记本电脑、家具等", required=True),
            TemplateField(key="goods_spec", label="规格型号", placeholder="品牌、型号、配置等", required=True),
            TemplateField(key="quantity", label="数量", placeholder="如：10台", required=True),
            TemplateField(key="unit_price", label="单价（元）", placeholder="如：5,000", required=True),
            TemplateField(key="total_price", label="总价（元）", placeholder="如：50,000", required=True),
            TemplateField(key="delivery_method", label="交付方式", placeholder="如：甲方送货/乙方自提/物流配送", required=True),
            TemplateField(key="delivery_date", label="交付日期", placeholder="如：2025年6月1日前", required=True),
            TemplateField(key="delivery_address", label="交付地点", placeholder="详细地址", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：一次性付款/分期付款", required=True),
            TemplateField(key="payment_deadline", label="付款期限", placeholder="如：合同签订后5个工作日内", required=True),
            TemplateField(key="quality_standard", label="质量标准", placeholder="如：国家标准/行业标准/双方约定", required=False),
            TemplateField(key="warranty_period", label="质保期", placeholder="如：1年/2年", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "标的物信息", "价款与支付", "交付与验收", "质量保证与售后服务", "风险转移与所有权保留", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份商品买卖合同，甲方为卖方{party_a}，乙方为买方{party_b}，商品为{goods_name}（规格：{goods_spec}），数量{quantity}，单价{unit_price}元，总价{total_price}元。交付方式为{delivery_method}，交付日期{delivery_date}，交付地点{delivery_address}。付款方式为{payment_method}，付款期限{payment_deadline}。",
        law_references=["《中华人民共和国民法典》合同编", "《中华人民共和国产品质量法》"],
    ),
    "civil_sale_house": ContractTemplate(
        id="civil_sale_house",
        name="房屋买卖合同",
        description="适用于二手房或商品房交易，涵盖房屋信息、产权、过户、交付等条款",
        category_id="civil",
        subcategory_id="civil_sale",
        fields=[
            TemplateField(key="party_a", label="卖方（甲方）", placeholder="卖方姓名/名称", required=True),
            TemplateField(key="party_b", label="买方（乙方）", placeholder="买方姓名/名称", required=True),
            TemplateField(key="house_address", label="房屋坐落", placeholder="详细地址", required=True),
            TemplateField(key="house_area", label="建筑面积（㎡）", placeholder="如：120.5", required=True),
            TemplateField(key="house_type", label="房屋类型", placeholder="如：住宅/商业/办公", required=True),
            TemplateField(key="house_cert", label="产权证号", placeholder="不动产权证书编号", required=True),
            TemplateField(key="total_price", label="成交价格（元）", placeholder="如：2,000,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：一次性付款/按揭贷款/分期", required=True),
            TemplateField(key="down_payment", label="首付款（元）", placeholder="如：600,000", required=False),
            TemplateField(key="transfer_date", label="过户时间", placeholder="如：合同签订后30日内", required=True),
            TemplateField(key="delivery_date", label="交房时间", placeholder="如：过户完成后5日内", required=True),
            TemplateField(key="facilities", label="附属设施", placeholder="如：车位、储藏室、家具家电等", required=False),
            TemplateField(key="mortgage_status", label="抵押状态", placeholder="如：无抵押/有抵押需解押", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "房屋基本情况", "成交价格与付款方式", "过户与交付", "产权保证与瑕疵担保", "税费承担", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份房屋买卖合同，甲方为卖方{party_a}，乙方为买方{party_b}，房屋位于{house_address}，建筑面积{house_area}㎡，类型{house_type}，产权证号{house_cert}，成交价{total_price}元，付款方式{payment_method}，过户时间{transfer_date}，交房时间{delivery_date}。",
        law_references=["《中华人民共和国民法典》合同编", "《中华人民共和国城市房地产管理法》", "《城市房地产转让管理规定》"],
    ),
    "civil_sale_vehicle": ContractTemplate(
        id="civil_sale_vehicle",
        name="机动车买卖合同",
        description="适用于二手车交易，涵盖车辆信息、车况、过户、交付等条款",
        category_id="civil",
        subcategory_id="civil_sale",
        fields=[
            TemplateField(key="party_a", label="卖方（甲方）", placeholder="卖方姓名/名称", required=True),
            TemplateField(key="party_b", label="买方（乙方）", placeholder="买方姓名/名称", required=True),
            TemplateField(key="vehicle_brand", label="品牌型号", placeholder="如：大众帕萨特 2022款", required=True),
            TemplateField(key="vehicle_plate", label="车牌号", placeholder="如：京A12345", required=True),
            TemplateField(key="vehicle_vin", label="车架号（VIN）", placeholder="17位车辆识别代号", required=True),
            TemplateField(key="mileage", label="行驶里程（公里）", placeholder="如：50,000", required=True),
            TemplateField(key="first_reg_date", label="初次登记日期", placeholder="如：2022年3月", required=True),
            TemplateField(key="total_price", label="成交价格（元）", placeholder="如：150,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：一次性付款", required=True),
            TemplateField(key="transfer_date", label="过户时间", placeholder="如：合同签订后7日内", required=True),
            TemplateField(key="vehicle_condition", label="车况说明", placeholder="如：无事故、无泡水、无火烧", required=False),
            TemplateField(key="insurance_info", label="保险情况", placeholder="如：交强险至2026年3月", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "车辆基本情况", "成交价格与付款方式", "过户与交付", "车辆状况保证", "税费与费用承担", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份机动车买卖合同，甲方为卖方{party_a}，乙方为买方{party_b}，车辆品牌{vehicle_brand}，车牌号{vehicle_plate}，车架号{vehicle_vin}，行驶里程{mileage}公里，初次登记{first_reg_date}，成交价{total_price}元。",
        law_references=["《中华人民共和国民法典》合同编", "《二手车流通管理办法》"],
    ),
    "civil_sale_equipment": ContractTemplate(
        id="civil_sale_equipment",
        name="设备采购合同",
        description="适用于企业设备购置，涵盖技术规格、安装调试、验收、培训等条款",
        category_id="civil",
        subcategory_id="civil_sale",
        fields=[
            TemplateField(key="party_a", label="供方（甲方）", placeholder="供应商名称", required=True),
            TemplateField(key="party_b", label="需方（乙方）", placeholder="采购方名称", required=True),
            TemplateField(key="equipment_name", label="设备名称", placeholder="如：数控机床", required=True),
            TemplateField(key="equipment_spec", label="规格型号", placeholder="详细技术参数", required=True),
            TemplateField(key="manufacturer", label="生产厂家", placeholder="制造商名称", required=True),
            TemplateField(key="quantity", label="数量", placeholder="如：3台", required=True),
            TemplateField(key="unit_price", label="单价（元）", placeholder="如：500,000", required=True),
            TemplateField(key="total_price", label="总价（元）", placeholder="如：1,500,000", required=True),
            TemplateField(key="delivery_date", label="交货日期", placeholder="如：合同签订后60日内", required=True),
            TemplateField(key="delivery_address", label="交货地点", placeholder="详细地址", required=True),
            TemplateField(key="install_debug", label="安装调试", placeholder="如：甲方负责安装调试", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：预付30%/到货60%/质保金10%", required=True),
            TemplateField(key="warranty_period", label="质保期", placeholder="如：验收合格后12个月", required=True),
            TemplateField(key="training", label="培训要求", placeholder="如：甲方提供操作培训", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "设备信息与技术规格", "价款与支付", "交货与运输", "安装调试与验收", "培训与售后服务", "质量保证", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份设备采购合同，甲方为供方{party_a}，乙方为需方{party_b}，设备为{equipment_name}（规格：{equipment_spec}，厂家：{manufacturer}），数量{quantity}，总价{total_price}元，交货日期{delivery_date}，付款方式{payment_method}，质保期{warranty_period}。",
        law_references=["《中华人民共和国民法典》合同编", "《中华人民共和国产品质量法》"],
    ),
    "civil_lease_house": ContractTemplate(
        id="civil_lease_house",
        name="房屋租赁合同",
        description="适用于住宅或商业用房租赁，涵盖租金、押金、维修、用途等条款",
        category_id="civil",
        subcategory_id="civil_lease",
        fields=[
            TemplateField(key="party_a", label="出租方（甲方）", placeholder="出租方姓名/名称", required=True),
            TemplateField(key="party_b", label="承租方（乙方）", placeholder="承租方姓名/名称", required=True),
            TemplateField(key="house_address", label="房屋坐落", placeholder="详细地址", required=True),
            TemplateField(key="house_area", label="建筑面积（㎡）", placeholder="如：90", required=True),
            TemplateField(key="house_type", label="房屋类型", placeholder="如：住宅/商铺/写字楼", required=True),
            TemplateField(key="lease_purpose", label="租赁用途", placeholder="如：居住/办公/经营", required=True),
            TemplateField(key="lease_term", label="租赁期限", placeholder="如：自2025年1月1日至2026年12月31日", required=True),
            TemplateField(key="monthly_rent", label="月租金（元）", placeholder="如：3,000", required=True),
            TemplateField(key="payment_cycle", label="支付周期", placeholder="如：季付/半年付/年付", required=True),
            TemplateField(key="deposit", label="押金（元）", placeholder="如：6,000（两个月租金）", required=True),
            TemplateField(key="facilities", label="附属设施", placeholder="如：家具家电清单", required=False),
            TemplateField(key="maintenance", label="维修责任", placeholder="如：甲方负责房屋主体，乙方负责日常维护", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "房屋基本情况", "租赁用途", "租赁期限", "租金与支付方式", "押金", "房屋维护与修缮", "合同变更与解除", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份房屋租赁合同，甲方为出租方{party_a}，乙方为承租方{party_b}，房屋位于{house_address}，面积{house_area}㎡，类型{house_type}，用途{lease_purpose}，租期{lease_term}，月租金{monthly_rent}元，押金{deposit}元。",
        law_references=["《中华人民共和国民法典》合同编", "《商品房屋租赁管理办法》"],
    ),
    "civil_lease_vehicle": ContractTemplate(
        id="civil_lease_vehicle",
        name="车辆租赁合同",
        description="适用于机动车租赁，涵盖车辆信息、租金、使用范围、保险等条款",
        category_id="civil",
        subcategory_id="civil_lease",
        fields=[
            TemplateField(key="party_a", label="出租方（甲方）", placeholder="出租方名称", required=True),
            TemplateField(key="party_b", label="承租方（乙方）", placeholder="承租方名称", required=True),
            TemplateField(key="vehicle_brand", label="车辆品牌型号", placeholder="如：丰田凯美瑞 2023款", required=True),
            TemplateField(key="vehicle_plate", label="车牌号", placeholder="如：京B88888", required=True),
            TemplateField(key="lease_term", label="租赁期限", placeholder="如：自2025年1月1日至2025年6月30日", required=True),
            TemplateField(key="monthly_rent", label="月租金（元）", placeholder="如：5,000", required=True),
            TemplateField(key="deposit", label="押金（元）", placeholder="如：10,000", required=True),
            TemplateField(key="mileage_limit", label="里程限制", placeholder="如：每月不超过3000公里", required=False),
            TemplateField(key="usage_scope", label="使用范围", placeholder="如：仅限北京市行政区域内", required=True),
            TemplateField(key="insurance", label="保险要求", placeholder="如：甲方投保交强险、商业险", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "租赁车辆信息", "租赁期限", "租金与支付方式", "押金", "车辆使用范围与限制", "保险与事故处理", "车辆维护与保养", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份车辆租赁合同，甲方为出租方{party_a}，乙方为承租方{party_b}，车辆{vehicle_brand}，车牌号{vehicle_plate}，租期{lease_term}，月租金{monthly_rent}元，押金{deposit}元，使用范围{usage_scope}。",
        law_references=["《中华人民共和国民法典》合同编"],
    ),
    "civil_lease_equipment": ContractTemplate(
        id="civil_lease_equipment",
        name="设备租赁合同",
        description="适用于机械设备租赁，涵盖设备信息、租金、操作、维护等条款",
        category_id="civil",
        subcategory_id="civil_lease",
        fields=[
            TemplateField(key="party_a", label="出租方（甲方）", placeholder="出租方名称", required=True),
            TemplateField(key="party_b", label="承租方（乙方）", placeholder="承租方名称", required=True),
            TemplateField(key="equipment_name", label="设备名称", placeholder="如：塔吊/挖掘机", required=True),
            TemplateField(key="equipment_spec", label="规格型号", placeholder="详细技术参数", required=True),
            TemplateField(key="quantity", label="数量", placeholder="如：2台", required=True),
            TemplateField(key="lease_term", label="租赁期限", placeholder="如：自2025年3月1日至2025年12月31日", required=True),
            TemplateField(key="monthly_rent", label="月租金（元）", placeholder="如：30,000", required=True),
            TemplateField(key="deposit", label="押金（元）", placeholder="如：60,000", required=True),
            TemplateField(key="delivery_address", label="使用地点", placeholder="详细地址", required=True),
            TemplateField(key="operator", label="操作人员", placeholder="如：甲方提供操作人员/乙方自行安排", required=True),
            TemplateField(key="maintenance", label="维修保养", placeholder="如：甲方负责大修，乙方负责日常保养", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "设备信息", "租赁期限", "租金与支付方式", "押金", "设备交付与归还", "操作与使用", "维修与保养", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份设备租赁合同，甲方为出租方{party_a}，乙方为承租方{party_b}，设备{equipment_name}（规格：{equipment_spec}），数量{quantity}，租期{lease_term}，月租金{monthly_rent}元。",
        law_references=["《中华人民共和国民法典》合同编"],
    ),
    "civil_lease_venue": ContractTemplate(
        id="civil_lease_venue",
        name="场地租赁合同",
        description="适用于厂房、仓库及活动场地租赁",
        category_id="civil",
        subcategory_id="civil_lease",
        fields=[
            TemplateField(key="party_a", label="出租方（甲方）", placeholder="出租方名称", required=True),
            TemplateField(key="party_b", label="承租方（乙方）", placeholder="承租方名称", required=True),
            TemplateField(key="venue_address", label="场地位置", placeholder="详细地址", required=True),
            TemplateField(key="venue_area", label="场地面积（㎡）", placeholder="如：500", required=True),
            TemplateField(key="venue_type", label="场地类型", placeholder="如：厂房/仓库/活动场地", required=True),
            TemplateField(key="lease_purpose", label="租赁用途", placeholder="如：仓储/生产/活动举办", required=True),
            TemplateField(key="lease_term", label="租赁期限", placeholder="如：自2025年1月1日至2027年12月31日", required=True),
            TemplateField(key="monthly_rent", label="月租金（元）", placeholder="如：15,000", required=True),
            TemplateField(key="deposit", label="押金（元）", placeholder="如：30,000", required=True),
            TemplateField(key="facilities", label="配套设施", placeholder="如：水电、消防、办公区等", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "场地基本情况", "租赁用途", "租赁期限", "租金与支付方式", "押金", "场地使用规范", "配套设施与维护", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份场地租赁合同，甲方为出租方{party_a}，乙方为承租方{party_b}，场地位于{venue_address}，面积{venue_area}㎡，类型{venue_type}，用途{lease_purpose}，租期{lease_term}，月租金{monthly_rent}元。",
        law_references=["《中华人民共和国民法典》合同编"],
    ),
    "civil_loan_private": ContractTemplate(
        id="civil_loan_private",
        name="民间借贷合同",
        description="适用于个人或企业间借贷，涵盖借款金额、利率、期限、担保等条款",
        category_id="civil",
        subcategory_id="civil_loan",
        fields=[
            TemplateField(key="party_a", label="出借人（甲方）", placeholder="出借人姓名/名称", required=True),
            TemplateField(key="party_b", label="借款人（乙方）", placeholder="借款人姓名/名称", required=True),
            TemplateField(key="loan_amount", label="借款金额（元）", placeholder="如：100,000", required=True),
            TemplateField(key="loan_purpose", label="借款用途", placeholder="如：经营周转/购房/教育", required=True),
            TemplateField(key="interest_rate", label="年利率（%）", placeholder="如：6（不超过LPR四倍）", required=True),
            TemplateField(key="loan_term", label="借款期限", placeholder="如：自2025年1月1日至2025年12月31日", required=True),
            TemplateField(key="repayment_method", label="还款方式", placeholder="如：到期一次还本付息/按月付息到期还本", required=True),
            TemplateField(key="guarantor", label="担保人", placeholder="如无担保填'无'", required=False),
            TemplateField(key="guarantee_method", label="担保方式", placeholder="如：连带责任保证/抵押", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "借款金额与用途", "借款期限", "利率与利息", "还款方式", "担保条款", "提前还款", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份民间借贷合同，甲方为出借人{party_a}，乙方为借款人{party_b}，借款金额{loan_amount}元，用途{loan_purpose}，年利率{interest_rate}%，借款期限{loan_term}，还款方式{repayment_method}。",
        law_references=["《中华人民共和国民法典》合同编借款合同章", "《最高人民法院关于审理民间借贷案件适用法律若干问题的规定》"],
    ),
    "civil_loan_bank": ContractTemplate(
        id="civil_loan_bank",
        name="银行借款合同",
        description="适用于银行贷款申请，涵盖贷款金额、利率、期限、担保等条款",
        category_id="civil",
        subcategory_id="civil_loan",
        fields=[
            TemplateField(key="party_a", label="贷款人（甲方/银行）", placeholder="银行名称", required=True),
            TemplateField(key="party_b", label="借款人（乙方）", placeholder="借款人姓名/名称", required=True),
            TemplateField(key="loan_amount", label="贷款金额（元）", placeholder="如：500,000", required=True),
            TemplateField(key="loan_purpose", label="贷款用途", placeholder="如：个人消费/经营/购房", required=True),
            TemplateField(key="interest_rate", label="贷款利率", placeholder="如：年利率4.35%/LPR+0.5%", required=True),
            TemplateField(key="loan_term", label="贷款期限", placeholder="如：36个月", required=True),
            TemplateField(key="repayment_method", label="还款方式", placeholder="如：等额本息/等额本金/先息后本", required=True),
            TemplateField(key="guarantee_method", label="担保方式", placeholder="如：抵押/质押/保证/信用", required=True),
            TemplateField(key="collateral", label="抵押物/质押物", placeholder="如：房产/存单等", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "贷款金额与用途", "贷款期限", "贷款利率", "贷款发放", "还款方式与还款计划", "担保条款", "借款人承诺", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份银行借款合同，甲方为贷款人{party_a}，乙方为借款人{party_b}，贷款金额{loan_amount}元，用途{loan_purpose}，利率{interest_rate}，期限{loan_term}，还款方式{repayment_method}，担保方式{guarantee_method}。",
        law_references=["《中华人民共和国民法典》合同编借款合同章", "《中华人民共和国商业银行法》", "《贷款通则》"],
    ),
    "civil_gift_property": ContractTemplate(
        id="civil_gift_property",
        name="财产赠与合同",
        description="适用于无偿财产赠与，涵盖赠与财产、交付、撤销权等条款",
        category_id="civil",
        subcategory_id="civil_gift",
        fields=[
            TemplateField(key="party_a", label="赠与人（甲方）", placeholder="赠与人姓名", required=True),
            TemplateField(key="party_b", label="受赠人（乙方）", placeholder="受赠人姓名", required=True),
            TemplateField(key="gift_property", label="赠与财产", placeholder="如：位于XX的房产/存款XX元", required=True),
            TemplateField(key="property_detail", label="财产详情", placeholder="详细描述赠与财产", required=True),
            TemplateField(key="delivery_method", label="交付方式", placeholder="如：产权过户/实物交付/转账", required=True),
            TemplateField(key="delivery_date", label="交付时间", placeholder="如：合同签订后30日内", required=True),
            TemplateField(key="condition", label="附条件/义务", placeholder="如无附条件填'无'", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "赠与财产", "交付方式与时间", "附条件/义务", "赠与撤销", "税费承担", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份财产赠与合同，甲方为赠与人{party_a}，乙方为受赠人{party_b}，赠与财产为{gift_property}，详情：{property_detail}，交付方式{delivery_method}，交付时间{delivery_date}。",
        law_references=["《中华人民共和国民法典》合同编赠与合同章"],
    ),
    "civil_gift_equity": ContractTemplate(
        id="civil_gift_equity",
        name="股权赠与合同",
        description="适用于公司股权无偿赠与，涵盖股权信息、变更登记、权利义务等条款",
        category_id="civil",
        subcategory_id="civil_gift",
        fields=[
            TemplateField(key="party_a", label="赠与人（甲方）", placeholder="赠与人姓名", required=True),
            TemplateField(key="party_b", label="受赠人（乙方）", placeholder="受赠人姓名", required=True),
            TemplateField(key="company_name", label="公司名称", placeholder="目标公司全称", required=True),
            TemplateField(key="equity_ratio", label="赠与股权比例（%）", placeholder="如：10", required=True),
            TemplateField(key="equity_amount", label="对应出资额（元）", placeholder="如：1,000,000", required=True),
            TemplateField(key="delivery_date", label="变更登记时间", placeholder="如：合同签订后30日内", required=True),
            TemplateField(key="condition", label="附条件/义务", placeholder="如无附条件填'无'", required=False),
            TemplateField(key="other_shareholder_consent", label="其他股东同意情况", placeholder="如：已取得其他股东过半数同意", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "赠与股权信息", "股权变更登记", "附条件/义务", "权利义务转移", "税费承担", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份股权赠与合同，甲方为赠与人{party_a}，乙方为受赠人{party_b}，赠与{company_name}的{equity_ratio}%股权（出资额{equity_amount}元），变更登记时间{delivery_date}。",
        law_references=["《中华人民共和国民法典》合同编赠与合同章", "《中华人民共和国公司法》"],
    ),
    "comm_service_consulting": ContractTemplate(
        id="comm_service_consulting",
        name="咨询服务合同",
        description="适用于专业咨询服务，涵盖咨询内容、成果、费用、保密等条款",
        category_id="commercial",
        subcategory_id="comm_service",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="咨询方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="consulting_scope", label="咨询内容与范围", placeholder="如：企业法律风险评估", required=True),
            TemplateField(key="consulting_form", label="咨询方式", placeholder="如：书面报告/现场咨询/视频会议", required=True),
            TemplateField(key="service_period", label="服务期限", placeholder="如：自2025年1月1日至2025年6月30日", required=True),
            TemplateField(key="total_fee", label="咨询费用（元）", placeholder="如：50,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：合同签订付50%/交付成果付50%", required=True),
            TemplateField(key="deliverables", label="交付成果", placeholder="如：咨询报告/意见书", required=True),
            TemplateField(key="confidentiality", label="保密要求", placeholder="如：双方对商业秘密互负保密义务", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "咨询内容与范围", "咨询方式", "服务期限", "交付成果", "咨询费用与支付", "保密条款", "知识产权", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份咨询服务合同，甲方为委托方{party_a}，乙方为咨询方{party_b}，咨询内容{consulting_scope}，方式{consulting_form}，期限{service_period}，费用{total_fee}元，交付成果{deliverables}。",
        law_references=["《中华人民共和国民法典》合同编委托合同章"],
    ),
    "comm_service_technical": ContractTemplate(
        id="comm_service_technical",
        name="技术服务合同",
        description="适用于技术支持或服务，涵盖技术内容、标准、验收、知识产权等条款",
        category_id="commercial",
        subcategory_id="comm_service",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="服务方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="service_content", label="技术服务内容", placeholder="如：系统运维/技术支持/技术开发", required=True),
            TemplateField(key="technical_standard", label="技术标准与要求", placeholder="如：响应时间不超过2小时", required=True),
            TemplateField(key="service_period", label="服务期限", placeholder="如：自2025年1月1日至2025年12月31日", required=True),
            TemplateField(key="total_fee", label="服务费用（元）", placeholder="如：200,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：按季度支付", required=True),
            TemplateField(key="acceptance_criteria", label="验收标准", placeholder="如：按双方确认的技术方案验收", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "技术服务内容", "技术标准与要求", "服务期限", "服务费用与支付", "验收标准与方式", "知识产权", "保密条款", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份技术服务合同，甲方为委托方{party_a}，乙方为服务方{party_b}，服务内容{service_content}，标准{technical_standard}，期限{service_period}，费用{total_fee}元。",
        law_references=["《中华人民共和国民法典》合同编技术合同章"],
    ),
    "comm_service_property": ContractTemplate(
        id="comm_service_property",
        name="物业服务合同",
        description="适用于物业管理服务，涵盖服务内容、标准、费用等条款",
        category_id="commercial",
        subcategory_id="comm_service",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="业主大会/开发商", required=True),
            TemplateField(key="party_b", label="物业服务方（乙方）", placeholder="物业公司名称", required=True),
            TemplateField(key="property_name", label="物业项目名称", placeholder="如：XX花园小区", required=True),
            TemplateField(key="property_address", label="物业坐落", placeholder="详细地址", required=True),
            TemplateField(key="property_area", label="物业管理面积（㎡）", placeholder="如：50,000", required=True),
            TemplateField(key="service_scope", label="服务内容", placeholder="如：安保/保洁/绿化/维修", required=True),
            TemplateField(key="service_period", label="服务期限", placeholder="如：自2025年1月1日至2027年12月31日", required=True),
            TemplateField(key="monthly_fee", label="物业费标准（元/㎡/月）", placeholder="如：2.5", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "物业基本情况", "服务内容与标准", "服务期限", "物业费及支付方式", "甲方权利义务", "乙方权利义务", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份物业服务合同，甲方为委托方{party_a}，乙方为物业服务方{party_b}，物业项目{property_name}，面积{property_area}㎡，服务内容{service_scope}，期限{service_period}，物业费{monthly_fee}元/㎡/月。",
        law_references=["《中华人民共和国民法典》合同编", "《物业管理条例》"],
    ),
    "comm_service_agency": ContractTemplate(
        id="comm_service_agency",
        name="委托代理合同",
        description="适用于委托代理业务，涵盖委托事项、权限、费用等条款",
        category_id="commercial",
        subcategory_id="comm_service",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="受托方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="entrust_matter", label="委托事项", placeholder="如：代理诉讼/代为办理XX手续", required=True),
            TemplateField(key="authority_scope", label="授权范围", placeholder="如：一般授权/特别授权", required=True),
            TemplateField(key="service_period", label="委托期限", placeholder="如：自合同签订至事项办理完毕", required=True),
            TemplateField(key="total_fee", label="代理费用（元）", placeholder="如：30,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：合同签订付50%/事项完结付50%", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "委托事项", "授权范围", "委托期限", "代理费用与支付", "甲方权利义务", "乙方权利义务", "转委托", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份委托代理合同，甲方为委托方{party_a}，乙方为受托方{party_b}，委托事项{entrust_matter}，授权范围{authority_scope}，期限{service_period}，费用{total_fee}元。",
        law_references=["《中华人民共和国民法典》合同编委托合同章"],
    ),
    "comm_processing_machining": ContractTemplate(
        id="comm_processing_machining",
        name="加工合同",
        description="适用于物料加工，涵盖加工要求、材料、质量、报酬等条款",
        category_id="commercial",
        subcategory_id="comm_processing",
        fields=[
            TemplateField(key="party_a", label="定作方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="承揽方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="processing_content", label="加工内容", placeholder="如：机械零件加工", required=True),
            TemplateField(key="material_provider", label="材料提供方", placeholder="如：甲方提供/乙方自备", required=True),
            TemplateField(key="quality_standard", label="质量标准", placeholder="如：按图纸/国家标准", required=True),
            TemplateField(key="quantity", label="加工数量", placeholder="如：1000件", required=True),
            TemplateField(key="total_fee", label="加工报酬（元）", placeholder="如：50,000", required=True),
            TemplateField(key="delivery_date", label="交付日期", placeholder="如：2025年6月30日前", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：交付验收后7日内付款", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "加工内容", "材料提供", "质量标准", "加工数量与报酬", "交付与验收", "付款方式", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份加工合同，甲方为定作方{party_a}，乙方为承揽方{party_b}，加工内容{processing_content}，材料由{material_provider}提供，质量标准{quality_standard}，数量{quantity}，报酬{total_fee}元。",
        law_references=["《中华人民共和国民法典》合同编承揽合同章"],
    ),
    "comm_processing_custom": ContractTemplate(
        id="comm_processing_custom",
        name="定制合同",
        description="适用于产品定制，涵盖定制要求、设计、验收等条款",
        category_id="commercial",
        subcategory_id="comm_processing",
        fields=[
            TemplateField(key="party_a", label="定作方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="承揽方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="custom_content", label="定制产品", placeholder="如：定制家具/定制服装", required=True),
            TemplateField(key="specification", label="规格要求", placeholder="详细规格、材质、颜色等", required=True),
            TemplateField(key="quantity", label="数量", placeholder="如：1套", required=True),
            TemplateField(key="total_fee", label="定制费用（元）", placeholder="如：80,000", required=True),
            TemplateField(key="delivery_date", label="交付日期", placeholder="如：2025年8月1日前", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：预付50%/交付付50%", required=True),
            TemplateField(key="design_confirmation", label="设计确认", placeholder="如：甲方确认设计图后开始制作", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "定制产品信息", "规格与设计", "费用与支付", "制作与交付", "验收标准", "知识产权", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份定制合同，甲方为定作方{party_a}，乙方为承揽方{party_b}，定制产品{custom_content}，规格{specification}，数量{quantity}，费用{total_fee}元，交付日期{delivery_date}。",
        law_references=["《中华人民共和国民法典》合同编承揽合同章"],
    ),
    "comm_processing_repair": ContractTemplate(
        id="comm_processing_repair",
        name="维修合同",
        description="适用于物品修缮，涵盖维修内容、费用、质保等条款",
        category_id="commercial",
        subcategory_id="comm_processing",
        fields=[
            TemplateField(key="party_a", label="定作方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="承揽方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="repair_item", label="维修物品", placeholder="如：中央空调/电梯/设备", required=True),
            TemplateField(key="repair_content", label="维修内容", placeholder="如：更换压缩机/大修", required=True),
            TemplateField(key="total_fee", label="维修费用（元）", placeholder="如：15,000", required=True),
            TemplateField(key="completion_date", label="完工日期", placeholder="如：2025年5月15日前", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：完工验收后7日内付款", required=True),
            TemplateField(key="warranty_period", label="维修质保期", placeholder="如：维修完成后6个月", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "维修物品与内容", "维修费用", "完工期限", "验收标准", "付款方式", "质保期", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份维修合同，甲方为定作方{party_a}，乙方为承揽方{party_b}，维修物品{repair_item}，内容{repair_content}，费用{total_fee}元，完工日期{completion_date}，质保期{warranty_period}。",
        law_references=["《中华人民共和国民法典》合同编承揽合同章"],
    ),
    "comm_constr_build": ContractTemplate(
        id="comm_constr_build",
        name="工程施工合同",
        description="适用于工程建设，涵盖工程范围、工期、价款、质量等条款",
        category_id="commercial",
        subcategory_id="comm_construction",
        fields=[
            TemplateField(key="party_a", label="发包方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="承包方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="project_name", label="工程名称", placeholder="如：XX大厦土建工程", required=True),
            TemplateField(key="project_location", label="工程地点", placeholder="详细地址", required=True),
            TemplateField(key="project_scope", label="工程范围", placeholder="如：土建、安装、装饰", required=True),
            TemplateField(key="total_price", label="合同价款（元）", placeholder="如：10,000,000", required=True),
            TemplateField(key="pricing_method", label="计价方式", placeholder="如：固定总价/固定单价/成本加酬金", required=True),
            TemplateField(key="start_date", label="开工日期", placeholder="如：2025年3月1日", required=True),
            TemplateField(key="end_date", label="竣工日期", placeholder="如：2026年3月1日", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：按工程进度付款", required=True),
            TemplateField(key="quality_standard", label="质量标准", placeholder="如：合格/优良", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "工程概况", "工程范围", "合同工期", "合同价款与支付", "材料设备供应", "工程质量与验收", "安全施工", "工程变更", "竣工结算", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份工程施工合同，甲方为发包方{party_a}，乙方为承包方{party_b}，工程名称{project_name}，地点{project_location}，范围{project_scope}，合同价{total_price}元，工期{start_date}至{end_date}。",
        law_references=["《中华人民共和国民法典》合同编建设工程合同章", "《中华人民共和国建筑法》", "《建设工程质量管理条例》"],
    ),
    "comm_constr_design": ContractTemplate(
        id="comm_constr_design",
        name="工程设计合同",
        description="适用于工程设计，涵盖设计内容、标准、成果、费用等条款",
        category_id="commercial",
        subcategory_id="comm_construction",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="设计方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="project_name", label="工程名称", placeholder="如：XX商业综合体", required=True),
            TemplateField(key="design_scope", label="设计范围", placeholder="如：方案设计/施工图设计", required=True),
            TemplateField(key="design_standard", label="设计标准", placeholder="如：国家现行规范", required=True),
            TemplateField(key="total_fee", label="设计费用（元）", placeholder="如：500,000", required=True),
            TemplateField(key="delivery_date", label="交付日期", placeholder="如：2025年6月30日前", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：合同签订付30%/交付付70%", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "工程概况", "设计范围与内容", "设计标准", "设计成果与交付", "设计费用与支付", "设计变更", "知识产权", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份工程设计合同，甲方为委托方{party_a}，乙方为设计方{party_b}，工程{project_name}，设计范围{design_scope}，费用{total_fee}元，交付日期{delivery_date}。",
        law_references=["《中华人民共和国民法典》合同编建设工程合同章", "《建设工程勘察设计管理条例》"],
    ),
    "comm_constr_supervise": ContractTemplate(
        id="comm_constr_supervise",
        name="工程监理合同",
        description="适用于工程监理，涵盖监理范围、内容、费用等条款",
        category_id="commercial",
        subcategory_id="comm_construction",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="监理方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="project_name", label="工程名称", placeholder="如：XX大厦", required=True),
            TemplateField(key="supervise_scope", label="监理范围", placeholder="如：施工阶段全过程监理", required=True),
            TemplateField(key="supervise_content", label="监理内容", placeholder="如：质量控制/进度控制/投资控制", required=True),
            TemplateField(key="service_period", label="监理期限", placeholder="如：自开工至竣工验收", required=True),
            TemplateField(key="total_fee", label="监理费用（元）", placeholder="如：300,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：按月支付", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "工程概况", "监理范围与内容", "监理期限", "监理费用与支付", "甲方权利义务", "乙方权利义务", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份工程监理合同，甲方为委托方{party_a}，乙方为监理方{party_b}，工程{project_name}，监理范围{supervise_scope}，费用{total_fee}元，期限{service_period}。",
        law_references=["《中华人民共和国民法典》合同编", "《建设工程质量管理条例》"],
    ),
    "comm_transport_cargo": ContractTemplate(
        id="comm_transport_cargo",
        name="货物运输合同",
        description="适用于公路、水路等货物物流运输",
        category_id="commercial",
        subcategory_id="comm_transport",
        fields=[
            TemplateField(key="party_a", label="托运方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="承运方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="cargo_name", label="货物名称", placeholder="如：电子产品/建材", required=True),
            TemplateField(key="cargo_weight", label="货物重量/体积", placeholder="如：5吨/20立方米", required=True),
            TemplateField(key="origin", label="起运地", placeholder="如：北京市朝阳区", required=True),
            TemplateField(key="destination", label="目的地", placeholder="如：上海市浦东新区", required=True),
            TemplateField(key="transport_method", label="运输方式", placeholder="如：公路/铁路/水路", required=True),
            TemplateField(key="transport_fee", label="运输费用（元）", placeholder="如：8,000", required=True),
            TemplateField(key="delivery_date", label="到达期限", placeholder="如：3日内到达", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：货到付款/预付", required=True),
            TemplateField(key="insurance", label="货物保险", placeholder="如：甲方自行投保/乙方代为投保", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "货物信息", "运输路线与方式", "运输期限", "运输费用与支付", "货物装卸与交接", "货物保险", "货物毁损灭失责任", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份货物运输合同，甲方为托运方{party_a}，乙方为承运方{party_b}，货物{cargo_name}（{cargo_weight}），从{origin}运至{destination}，方式{transport_method}，费用{transport_fee}元。",
        law_references=["《中华人民共和国民法典》合同编运输合同章"],
    ),
    "comm_transport_passenger": ContractTemplate(
        id="comm_transport_passenger",
        name="旅客运输合同",
        description="适用于客运服务",
        category_id="commercial",
        subcategory_id="comm_transport",
        fields=[
            TemplateField(key="party_a", label="承运方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="旅客/包车方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="transport_type", label="运输类型", placeholder="如：包车/班车/旅游客运", required=True),
            TemplateField(key="route", label="运输路线", placeholder="如：北京至天津往返", required=True),
            TemplateField(key="departure_date", label="出发日期", placeholder="如：2025年5月1日", required=True),
            TemplateField(key="passenger_count", label="旅客人数", placeholder="如：30人", required=True),
            TemplateField(key="total_fee", label="运输费用（元）", placeholder="如：15,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：预付全款", required=True),
            TemplateField(key="vehicle_info", label="车辆信息", placeholder="如：49座大巴", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "运输类型与路线", "出发时间", "旅客信息", "运输费用与支付", "承运方义务", "旅客义务", "安全责任", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份旅客运输合同，甲方为承运方{party_a}，乙方为旅客/包车方{party_b}，类型{transport_type}，路线{route}，日期{departure_date}，人数{passenger_count}，费用{total_fee}元。",
        law_references=["《中华人民共和国民法典》合同编运输合同章", "《中华人民共和国道路运输条例》"],
    ),
    "comm_storage_custody": ContractTemplate(
        id="comm_storage_custody",
        name="仓储保管合同",
        description="适用于货物的存储与保管服务",
        category_id="commercial",
        subcategory_id="comm_storage",
        fields=[
            TemplateField(key="party_a", label="存货方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="保管方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="cargo_name", label="存储货物", placeholder="如：电子产品/食品", required=True),
            TemplateField(key="cargo_quantity", label="货物数量/重量", placeholder="如：1000箱/5吨", required=True),
            TemplateField(key="warehouse_address", label="仓储地点", placeholder="详细地址", required=True),
            TemplateField(key="storage_area", label="仓储面积（㎡）", placeholder="如：200", required=True),
            TemplateField(key="storage_period", label="存储期限", placeholder="如：自2025年1月1日至2025年12月31日", required=True),
            TemplateField(key="storage_fee", label="仓储费用（元/月）", placeholder="如：10,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：按月支付", required=True),
            TemplateField(key="storage_conditions", label="存储条件", placeholder="如：常温/冷藏/防潮", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "仓储货物信息", "仓储地点与条件", "存储期限", "仓储费用与支付", "货物入库与出库", "保管要求", "货物毁损灭失责任", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份仓储保管合同，甲方为存货方{party_a}，乙方为保管方{party_b}，存储货物{cargo_name}（{cargo_quantity}），地点{warehouse_address}，期限{storage_period}，月费用{storage_fee}元。",
        law_references=["《中华人民共和国民法典》合同编仓储合同章"],
    ),
    "labor_fulltime": ContractTemplate(
        id="labor_fulltime",
        name="全日制固定期限劳动合同",
        description="适用于常规全职员工用工",
        category_id="labor",
        subcategory_id="labor_contract",
        fields=[
            TemplateField(key="employer", label="用人单位（甲方）", placeholder="公司名称", required=True),
            TemplateField(key="employee", label="劳动者（乙方）", placeholder="员工姓名", required=True),
            TemplateField(key="position", label="工作岗位", placeholder="如：软件工程师", required=True),
            TemplateField(key="department", label="所属部门", placeholder="如：技术部", required=True),
            TemplateField(key="work_place", label="工作地点", placeholder="如：北京市海淀区", required=True),
            TemplateField(key="contract_term", label="合同期限", placeholder="如：自2025年1月1日至2028年12月31日", required=True),
            TemplateField(key="probation_period", label="试用期", placeholder="如：3个月/6个月", required=True),
            TemplateField(key="monthly_salary", label="月工资（元）", placeholder="如：15,000", required=True),
            TemplateField(key="salary_structure", label="薪资构成", placeholder="如：基本工资+绩效+补贴", required=False),
            TemplateField(key="work_hours", label="工时制度", placeholder="如：标准工时/综合计算工时", required=True),
            TemplateField(key="social_insurance", label="社会保险", placeholder="如：依法缴纳五险一金", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "合同期限", "工作内容与工作地点", "工作时间和休息休假", "劳动报酬", "社会保险和福利待遇", "劳动保护、劳动条件和职业危害防护", "合同变更、解除与终止", "保密与竞业限制", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份全日制固定期限劳动合同，甲方为用人单位{employer}，乙方为劳动者{employee}，岗位{position}，部门{department}，工作地点{work_place}，合同期限{contract_term}，试用期{probation_period}，月工资{monthly_salary}元。",
        law_references=["《中华人民共和国劳动法》", "《中华人民共和国劳动合同法》"],
    ),
    "labor_parttime": ContractTemplate(
        id="labor_parttime",
        name="非全日制用工合同",
        description="适用于兼职或钟点工",
        category_id="labor",
        subcategory_id="labor_contract",
        fields=[
            TemplateField(key="employer", label="用人单位（甲方）", placeholder="公司名称", required=True),
            TemplateField(key="employee", label="劳动者（乙方）", placeholder="员工姓名", required=True),
            TemplateField(key="position", label="工作岗位", placeholder="如：保洁员/收银员", required=True),
            TemplateField(key="work_hours", label="每日工作时间", placeholder="如：4小时", required=True),
            TemplateField(key="work_days", label="每周工作天数", placeholder="如：5天", required=True),
            TemplateField(key="hourly_wage", label="小时工资（元/小时）", placeholder="如：25", required=True),
            TemplateField(key="payment_cycle", label="结算周期", placeholder="如：每15日结算一次", required=True),
            TemplateField(key="work_place", label="工作地点", placeholder="详细地址", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "工作内容与地点", "工作时间", "劳动报酬", "社会保险", "劳动保护", "合同解除", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份非全日制用工合同，甲方为用人单位{employer}，乙方为劳动者{employee}，岗位{position}，每日工作{work_hours}小时，小时工资{hourly_wage}元，结算周期{payment_cycle}。",
        law_references=["《中华人民共和国劳动合同法》非全日制用工一节"],
    ),
    "labor_dispatch": ContractTemplate(
        id="labor_dispatch",
        name="劳务派遣合同",
        description="适用于劳务派遣形式用工",
        category_id="labor",
        subcategory_id="labor_contract",
        fields=[
            TemplateField(key="party_a", label="劳务派遣单位（甲方）", placeholder="派遣公司名称", required=True),
            TemplateField(key="party_b", label="被派遣劳动者（乙方）", placeholder="员工姓名", required=True),
            TemplateField(key="party_c", label="用工单位（丙方）", placeholder="实际用工单位名称", required=True),
            TemplateField(key="position", label="工作岗位", placeholder="如：客服/保安", required=True),
            TemplateField(key="work_place", label="工作地点", placeholder="详细地址", required=True),
            TemplateField(key="dispatch_term", label="派遣期限", placeholder="如：自2025年1月1日至2026年12月31日", required=True),
            TemplateField(key="monthly_salary", label="月工资（元）", placeholder="如：6,000", required=True),
            TemplateField(key="social_insurance", label="社会保险", placeholder="如：甲方依法缴纳", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "派遣期限", "工作岗位与地点", "劳动报酬", "社会保险", "用工单位义务", "派遣单位义务", "劳动者权利义务", "合同解除", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份劳务派遣合同，甲方为派遣单位{party_a}，乙方为劳动者{party_b}，丙方为用工单位{party_c}，岗位{position}，派遣期限{dispatch_term}，月工资{monthly_salary}元。",
        law_references=["《中华人民共和国劳动合同法》劳务派遣一节", "《劳务派遣暂行规定》"],
    ),
    "labor_hr_noncompete": ContractTemplate(
        id="labor_hr_noncompete",
        name="保密及竞业限制协议",
        description="适用于涉密或核心岗位员工",
        category_id="labor",
        subcategory_id="labor_hr",
        fields=[
            TemplateField(key="employer", label="用人单位（甲方）", placeholder="公司名称", required=True),
            TemplateField(key="employee", label="员工（乙方）", placeholder="员工姓名", required=True),
            TemplateField(key="position", label="岗位", placeholder="如：技术总监/销售经理", required=True),
            TemplateField(key="confidential_scope", label="保密范围", placeholder="如：技术秘密/商业秘密/客户信息", required=True),
            TemplateField(key="noncompete_term", label="竞业限制期限", placeholder="如：离职后2年", required=True),
            TemplateField(key="noncompete_scope", label="竞业限制范围", placeholder="如：同行业竞争企业", required=True),
            TemplateField(key="compensation", label="竞业限制补偿金（元/月）", placeholder="如：5,000", required=True),
            TemplateField(key="penalty", label="违约金（元）", placeholder="如：200,000", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "保密范围与义务", "竞业限制范围", "竞业限制期限", "竞业限制补偿金", "违约责任", "协议解除", "争议解决", "其他约定"],
        prompt_template="请生成一份保密及竞业限制协议，甲方为用人单位{employer}，乙方为员工{employee}，岗位{position}，保密范围{confidential_scope}，竞业限制期限{noncompete_term}，补偿金{compensation}元/月，违约金{penalty}元。",
        law_references=["《中华人民共和国劳动合同法》第23-24条", "《最高人民法院关于审理劳动争议案件适用法律问题的解释》"],
    ),
    "labor_hr_termination": ContractTemplate(
        id="labor_hr_termination",
        name="解除劳动关系协议书",
        description="适用于劳资双方协商一致离职",
        category_id="labor",
        subcategory_id="labor_hr",
        fields=[
            TemplateField(key="employer", label="用人单位（甲方）", placeholder="公司名称", required=True),
            TemplateField(key="employee", label="员工（乙方）", placeholder="员工姓名", required=True),
            TemplateField(key="position", label="原岗位", placeholder="如：市场经理", required=True),
            TemplateField(key="entry_date", label="入职日期", placeholder="如：2020年3月1日", required=True),
            TemplateField(key="termination_date", label="解除日期", placeholder="如：2025年4月30日", required=True),
            TemplateField(key="termination_reason", label="解除原因", placeholder="如：协商一致", required=True),
            TemplateField(key="compensation", label="经济补偿金（元）", placeholder="如：80,000", required=True),
            TemplateField(key="salary_settlement", label="工资结算", placeholder="如：结清至解除日", required=True),
            TemplateField(key="handover", label="工作交接", placeholder="如：乙方于解除日前完成交接", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "劳动关系基本情况", "解除原因", "解除日期", "经济补偿", "工资及福利结算", "工作交接", "社保公积金", "保密义务", "争议处理", "其他约定"],
        prompt_template="请生成一份解除劳动关系协议书，甲方为用人单位{employer}，乙方为员工{employee}，原岗位{position}，入职{entry_date}，解除日期{termination_date}，原因{termination_reason}，补偿金{compensation}元。",
        law_references=["《中华人民共和国劳动合同法》第36条、第46-47条"],
    ),
    "labor_hr_option": ContractTemplate(
        id="labor_hr_option",
        name="员工期权激励协议",
        description="适用于核心骨干股权期权激励",
        category_id="labor",
        subcategory_id="labor_hr",
        fields=[
            TemplateField(key="party_a", label="公司（甲方）", placeholder="公司名称", required=True),
            TemplateField(key="party_b", label="激励对象（乙方）", placeholder="员工姓名", required=True),
            TemplateField(key="position", label="岗位", placeholder="如：CTO/VP", required=True),
            TemplateField(key="option_amount", label="期权数量（股）", placeholder="如：100,000", required=True),
            TemplateField(key="option_ratio", label="占公司总股本比例（%）", placeholder="如：1.5", required=True),
            TemplateField(key="exercise_price", label="行权价格（元/股）", placeholder="如：1.00", required=True),
            TemplateField(key="vesting_schedule", label="成熟安排", placeholder="如：4年成熟，每年25%", required=True),
            TemplateField(key="exercise_period", label="行权期限", placeholder="如：成熟后3年内", required=True),
            TemplateField(key="exit_conditions", label="退出机制", placeholder="如：离职时公司回购", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "期权授予", "行权价格", "成熟安排", "行权方式与期限", "期权调整", "退出机制", "保密义务", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份员工期权激励协议，甲方为公司{party_a}，乙方为激励对象{party_b}，岗位{position}，期权{option_amount}股（占比{option_ratio}%），行权价{exercise_price}元/股，成熟安排{vesting_schedule}。",
        law_references=["《中华人民共和国公司法》", "《中华人民共和国证券法》"],
    ),
    "ip_patent_transfer": ContractTemplate(
        id="ip_patent_transfer",
        name="专利权转让合同",
        description="适用于专利所有权的变更买卖",
        category_id="ip",
        subcategory_id="ip_license",
        fields=[
            TemplateField(key="party_a", label="转让方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="受让方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="patent_name", label="专利名称", placeholder="如：一种XX方法", required=True),
            TemplateField(key="patent_no", label="专利号", placeholder="如：ZL202310XXXXXX.X", required=True),
            TemplateField(key="patent_type", label="专利类型", placeholder="如：发明专利/实用新型/外观设计", required=True),
            TemplateField(key="transfer_price", label="转让费用（元）", placeholder="如：500,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：合同签订付50%/登记完成付50%", required=True),
            TemplateField(key="transfer_date", label="登记时间", placeholder="如：合同签订后30日内", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "专利信息", "转让范围", "转让费用与支付", "专利权转移登记", "技术资料交付", "权利保证", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份专利权转让合同，甲方为转让方{party_a}，乙方为受让方{party_b}，专利{patent_name}（专利号{patent_no}，类型{patent_type}），转让费{transfer_price}元。",
        law_references=["《中华人民共和国专利法》", "《中华人民共和国民法典》合同编技术合同章"],
    ),
    "ip_trademark_license": ContractTemplate(
        id="ip_trademark_license",
        name="商标使用许可合同",
        description="适用于商标的授权使用",
        category_id="ip",
        subcategory_id="ip_license",
        fields=[
            TemplateField(key="party_a", label="许可方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="被许可方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="trademark_name", label="商标名称", placeholder="如：XX品牌", required=True),
            TemplateField(key="trademark_no", label="商标注册号", placeholder="如：第XXXXXXX号", required=True),
            TemplateField(key="license_type", label="许可类型", placeholder="如：独占许可/排他许可/普通许可", required=True),
            TemplateField(key="license_scope", label="许可使用范围", placeholder="如：仅限于XX类商品", required=True),
            TemplateField(key="license_term", label="许可期限", placeholder="如：自2025年1月1日至2027年12月31日", required=True),
            TemplateField(key="license_fee", label="许可费用（元）", placeholder="如：200,000/年", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：按年支付", required=True),
            TemplateField(key="quality_control", label="质量监督", placeholder="如：甲方有权监督商品质量", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "商标信息", "许可类型与范围", "许可期限", "许可费用与支付", "商品质量监督", "商标使用规范", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份商标使用许可合同，甲方为许可方{party_a}，乙方为被许可方{party_b}，商标{trademark_name}（注册号{trademark_no}），许可类型{license_type}，范围{license_scope}，期限{license_term}，费用{license_fee}。",
        law_references=["《中华人民共和国商标法》", "《商标法实施条例》"],
    ),
    "ip_copyright_transfer": ContractTemplate(
        id="ip_copyright_transfer",
        name="著作权转让合同",
        description="适用于版权的买断交易",
        category_id="ip",
        subcategory_id="ip_license",
        fields=[
            TemplateField(key="party_a", label="转让方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="受让方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="work_name", label="作品名称", placeholder="如：XX小说/XX软件", required=True),
            TemplateField(key="work_type", label="作品类型", placeholder="如：文字作品/软件/美术作品", required=True),
            TemplateField(key="transfer_scope", label="转让权利范围", placeholder="如：全部财产权/部分权利", required=True),
            TemplateField(key="transfer_price", label="转让费用（元）", placeholder="如：300,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：一次性付款", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "作品信息", "转让权利范围", "转让费用与支付", "权利保证", "署名权保留", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份著作权转让合同，甲方为转让方{party_a}，乙方为受让方{party_b}，作品{work_name}（类型{work_type}），转让范围{transfer_scope}，费用{transfer_price}元。",
        law_references=["《中华人民共和国著作权法》"],
    ),
    "ip_software_license": ContractTemplate(
        id="ip_software_license",
        name="软件著作权许可使用协议",
        description="适用于软件的授权使用",
        category_id="ip",
        subcategory_id="ip_license",
        fields=[
            TemplateField(key="party_a", label="许可方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="被许可方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="software_name", label="软件名称", placeholder="如：XX管理系统V3.0", required=True),
            TemplateField(key="license_type", label="许可类型", placeholder="如：独占许可/非独占许可", required=True),
            TemplateField(key="license_scope", label="许可范围", placeholder="如：乙方内部使用/可再许可", required=True),
            TemplateField(key="license_term", label="许可期限", placeholder="如：永久/3年", required=True),
            TemplateField(key="license_fee", label="许可费用（元）", placeholder="如：100,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：一次性付款/年度付费", required=True),
            TemplateField(key="user_count", label="授权用户数", placeholder="如：不限/50人", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "软件信息", "许可类型与范围", "许可期限", "许可费用与支付", "使用限制", "技术支持与维护", "知识产权保护", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份软件著作权许可使用协议，甲方为许可方{party_a}，乙方为被许可方{party_b}，软件{software_name}，许可类型{license_type}，范围{license_scope}，期限{license_term}，费用{license_fee}元。",
        law_references=["《中华人民共和国著作权法》", "《计算机软件保护条例》"],
    ),
    "ip_software_dev": ContractTemplate(
        id="ip_software_dev",
        name="委托软件开发合同",
        description="适用于定制化软件的委托开发项目",
        category_id="ip",
        subcategory_id="ip_dev",
        fields=[
            TemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="开发方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="project_name", label="项目名称", placeholder="如：XX电商平台开发", required=True),
            TemplateField(key="dev_scope", label="开发范围与功能", placeholder="如：前端+后端+数据库设计", required=True),
            TemplateField(key="tech_stack", label="技术要求", placeholder="如：Vue3+Python+MySQL", required=True),
            TemplateField(key="total_fee", label="开发费用（元）", placeholder="如：500,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：预付30%/中期40%/验收30%", required=True),
            TemplateField(key="dev_period", label="开发周期", placeholder="如：6个月", required=True),
            TemplateField(key="acceptance_criteria", label="验收标准", placeholder="如：按需求文档验收", required=True),
            TemplateField(key="ip_ownership", label="知识产权归属", placeholder="如：归甲方所有", required=True),
            TemplateField(key="warranty_period", label="维护期", placeholder="如：验收后12个月免费维护", required=False),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "项目概况", "开发范围与功能", "技术要求", "开发周期与里程碑", "开发费用与支付", "验收标准与方式", "知识产权归属", "保密条款", "维护与支持", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份委托软件开发合同，甲方为委托方{party_a}，乙方为开发方{party_b}，项目{project_name}，范围{dev_scope}，费用{total_fee}元，周期{dev_period}，知识产权归{ip_ownership}。",
        law_references=["《中华人民共和国民法典》合同编技术合同章", "《计算机软件保护条例》"],
    ),
    "invest_capital_increase": ContractTemplate(
        id="invest_capital_increase",
        name="增资扩股协议",
        description="适用于引入新股东为公司增资",
        category_id="investment",
        subcategory_id="invest_equity",
        fields=[
            TemplateField(key="company_name", label="目标公司", placeholder="公司全称", required=True),
            TemplateField(key="original_shareholders", label="原股东", placeholder="如：张三、李四", required=True),
            TemplateField(key="new_investor", label="新增资方", placeholder="投资方名称", required=True),
            TemplateField(key="capital_amount", label="增资金额（元）", placeholder="如：10,000,000", required=True),
            TemplateField(key="equity_ratio", label="增资后持股比例（%）", placeholder="如：20", required=True),
            TemplateField(key="registered_capital", label="增资后注册资本（元）", placeholder="如：12,500,000", required=True),
            TemplateField(key="payment_method", label="出资方式", placeholder="如：现金", required=True),
            TemplateField(key="payment_deadline", label="出资期限", placeholder="如：协议签订后30日内", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "增资方案", "增资价格与金额", "出资方式与期限", "股权变更登记", "公司治理", "利润分配", "陈述与保证", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份增资扩股协议，目标公司{company_name}，原股东{original_shareholders}，新增资方{new_investor}，增资金额{capital_amount}元，增资后持股{equity_ratio}%。",
        law_references=["《中华人民共和国公司法》"],
    ),
    "invest_equity_transfer": ContractTemplate(
        id="invest_equity_transfer",
        name="股权转让协议",
        description="适用于老股东向他人转让股份",
        category_id="investment",
        subcategory_id="invest_equity",
        fields=[
            TemplateField(key="party_a", label="转让方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="受让方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="company_name", label="目标公司", placeholder="公司全称", required=True),
            TemplateField(key="equity_ratio", label="转让股权比例（%）", placeholder="如：30", required=True),
            TemplateField(key="equity_amount", label="对应出资额（元）", placeholder="如：3,000,000", required=True),
            TemplateField(key="transfer_price", label="转让价格（元）", placeholder="如：15,000,000", required=True),
            TemplateField(key="payment_method", label="付款方式", placeholder="如：协议签订付50%/变更登记付50%", required=True),
            TemplateField(key="transfer_date", label="变更登记时间", placeholder="如：协议签订后30日内", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "股权转让内容", "转让价格与支付", "股权变更登记", "陈述与保证", "债务承担", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份股权转让协议，甲方为转让方{party_a}，乙方为受让方{party_b}，目标公司{company_name}，转让{equity_ratio}%股权（出资额{equity_amount}元），转让价{transfer_price}元。",
        law_references=["《中华人民共和国公司法》"],
    ),
    "invest_term_sheet": ContractTemplate(
        id="invest_term_sheet",
        name="投资意向书/Term Sheet",
        description="适用于早期投资意向与核心条款锁定",
        category_id="investment",
        subcategory_id="invest_equity",
        fields=[
            TemplateField(key="investor", label="投资方", placeholder="投资方名称", required=True),
            TemplateField(key="company_name", label="目标公司", placeholder="公司全称", required=True),
            TemplateField(key="founder", label="创始人", placeholder="创始人姓名", required=True),
            TemplateField(key="invest_amount", label="投资金额（元）", placeholder="如：5,000,000", required=True),
            TemplateField(key="valuation", label="投前估值（元）", placeholder="如：20,000,000", required=True),
            TemplateField(key="equity_ratio", label="投资后持股比例（%）", placeholder="如：20", required=True),
            TemplateField(key="invest_form", label="投资方式", placeholder="如：增资", required=True),
            TemplateField(key="board_seats", label="董事会席位", placeholder="如：投资方委派1名董事", required=False),
            TemplateField(key="anti_dilution", label="反稀释条款", placeholder="如：完全棘轮/加权平均", required=False),
            TemplateField(key="liquidation_preference", label="清算优先权", placeholder="如：1倍参与型", required=False),
            TemplateField(key="exclusivity_period", label="排他期", placeholder="如：60天", required=False),
        ],
        outline_sections=["投资方与目标公司", "投资金额与估值", "投资方式", "股权比例", "董事会与治理", "投资者权利", "反稀释与保护条款", "排他期", "保密条款", "约束力说明"],
        prompt_template="请生成一份投资意向书，投资方{investor}，目标公司{company_name}，创始人{founder}，投资金额{invest_amount}元，投前估值{valuation}元，持股{equity_ratio}%。",
        law_references=["《中华人民共和国公司法》"],
    ),
    "invest_partnership": ContractTemplate(
        id="invest_partnership",
        name="合伙协议",
        description="适用于合伙企业的设立与日常运营",
        category_id="investment",
        subcategory_id="invest_equity",
        fields=[
            TemplateField(key="partners", label="合伙人", placeholder="如：张三、李四、王五", required=True),
            TemplateField(key="partnership_name", label="合伙企业名称", placeholder="如：XX投资合伙企业（有限合伙）", required=True),
            TemplateField(key="partnership_type", label="合伙类型", placeholder="如：普通合伙/有限合伙", required=True),
            TemplateField(key="business_scope", label="经营范围", placeholder="如：股权投资", required=True),
            TemplateField(key="total_capital", label="合伙出资总额（元）", placeholder="如：10,000,000", required=True),
            TemplateField(key="capital_contribution", label="各合伙人出资", placeholder="如：张三出资100万（GP），李四出资900万（LP）", required=True),
            TemplateField(key="profit_distribution", label="利润分配", placeholder="如：按出资比例分配", required=True),
            TemplateField(key="management", label="执行事务合伙人", placeholder="如：张三", required=True),
            TemplateField(key="partnership_term", label="合伙期限", placeholder="如：10年", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "合伙企业概况", "合伙人出资", "利润分配与亏损分担", "合伙事务执行", "入伙与退伙", "合伙期限", "解散与清算", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份合伙协议，合伙人{partners}，企业名称{partnership_name}，类型{partnership_type}，出资总额{total_capital}元，利润分配{profit_distribution}，执行事务合伙人{management}。",
        law_references=["《中华人民共和国合伙企业法》"],
    ),
    "invest_guarantee": ContractTemplate(
        id="invest_guarantee",
        name="保证担保合同",
        description="适用于为债务提供连带责任或一般保证",
        category_id="investment",
        subcategory_id="invest_guarantee",
        fields=[
            TemplateField(key="creditor", label="债权人（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="debtor", label="债务人（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="guarantor", label="保证人（丙方）", placeholder="丙方名称", required=True),
            TemplateField(key="principal_debt", label="主债权金额（元）", placeholder="如：1,000,000", required=True),
            TemplateField(key="guarantee_type", label="保证方式", placeholder="如：连带责任保证/一般保证", required=True),
            TemplateField(key="guarantee_scope", label="保证范围", placeholder="如：主债权及利息、违约金、损害赔偿金等", required=True),
            TemplateField(key="guarantee_period", label="保证期间", placeholder="如：主债务履行期届满之日起2年", required=True),
            TemplateField(key="debt_term", label="主债务履行期限", placeholder="如：2025年12月31日前", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["合同主体", "主债权情况", "保证方式", "保证范围", "保证期间", "保证人权利", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份保证担保合同，债权人{creditor}，债务人{debtor}，保证人{guarantor}，主债权{principal_debt}元，保证方式{guarantee_type}，保证范围{guarantee_scope}，保证期间{guarantee_period}。",
        law_references=["《中华人民共和国民法典》合同编保证合同章"],
    ),
    "other_settlement": ContractTemplate(
        id="other_settlement",
        name="和解协议书",
        description="适用于民商事纠纷的协商解决",
        category_id="other",
        subcategory_id="other_common",
        fields=[
            TemplateField(key="party_a", label="甲方", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="乙方", placeholder="乙方名称", required=True),
            TemplateField(key="dispute_background", label="纠纷背景", placeholder="简述纠纷经过", required=True),
            TemplateField(key="settlement_content", label="和解内容", placeholder="如：乙方赔偿甲方XX元", required=True),
            TemplateField(key="payment_method", label="履行方式", placeholder="如：一次性支付/分期支付", required=True),
            TemplateField(key="payment_deadline", label="履行期限", placeholder="如：协议签订后15日内", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "纠纷背景", "和解内容", "履行方式与期限", "权利放弃", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份和解协议书，甲方{party_a}，乙方{party_b}，纠纷背景{dispute_background}，和解内容{settlement_content}，履行方式{payment_method}，期限{payment_deadline}。",
        law_references=["《中华人民共和国民法典》"],
    ),
    "other_authorization": ContractTemplate(
        id="other_authorization",
        name="授权委托书",
        description="适用于委托他人代为办理特定事项",
        category_id="other",
        subcategory_id="other_common",
        fields=[
            TemplateField(key="principal", label="委托人", placeholder="委托人姓名", required=True),
            TemplateField(key="agent", label="受托人", placeholder="受托人姓名", required=True),
            TemplateField(key="agent_id", label="受托人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            TemplateField(key="entrust_matter", label="委托事项", placeholder="如：代为办理房产过户手续", required=True),
            TemplateField(key="authority_scope", label="授权范围", placeholder="如：全权代理/仅限XX事项", required=True),
            TemplateField(key="valid_period", label="委托期限", placeholder="如：自2025年1月1日至2025年12月31日", required=True),
            TemplateField(key="special_auth", label="特别授权", placeholder="如：代为签署文件/代为收取款项", required=False),
        ],
        outline_sections=["委托人信息", "受托人信息", "委托事项", "授权范围", "委托期限", "特别授权", "委托人承诺"],
        prompt_template="请生成一份授权委托书，委托人{principal}，受托人{agent}（身份证{agent_id}），委托事项{entrust_matter}，授权范围{authority_scope}，期限{valid_period}。",
        law_references=["《中华人民共和国民法典》委托代理相关条文"],
    ),
    "other_prenuptial": ContractTemplate(
        id="other_prenuptial",
        name="婚前/婚内财产协议",
        description="适用于夫妻财产归属的特别约定",
        category_id="other",
        subcategory_id="other_common",
        fields=[
            TemplateField(key="party_a", label="男方", placeholder="男方姓名", required=True),
            TemplateField(key="party_b", label="女方", placeholder="女方姓名", required=True),
            TemplateField(key="agreement_type", label="协议类型", placeholder="如：婚前财产协议/婚内财产协议", required=True),
            TemplateField(key="property_a", label="男方财产", placeholder="如：位于XX的房产、XX公司股权", required=True),
            TemplateField(key="property_b", label="女方财产", placeholder="如：XX存款、XX车辆", required=True),
            TemplateField(key="joint_property", label="共同财产约定", placeholder="如：婚后收入归各自所有/共同所有", required=True),
            TemplateField(key="debt_agreement", label="债务约定", placeholder="如：各自债务各自承担", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "协议类型", "男方婚前/个人财产", "女方婚前/个人财产", "婚后财产归属约定", "债务约定", "变更与补充", "争议解决", "其他约定"],
        prompt_template="请生成一份{agreement_type}，男方{party_a}，女方{party_b}，男方财产{property_a}，女方财产{property_b}，婚后财产约定{joint_property}，债务约定{debt_agreement}。",
        law_references=["《中华人民共和国民法典》婚姻家庭编第1065条"],
    ),
    "other_unjust_enrichment": ContractTemplate(
        id="other_unjust_enrichment",
        name="不当得利返还协议",
        description="适用于错打款等不当得利的返还",
        category_id="other",
        subcategory_id="other_common",
        fields=[
            TemplateField(key="party_a", label="受损方（甲方）", placeholder="甲方名称", required=True),
            TemplateField(key="party_b", label="得利方（乙方）", placeholder="乙方名称", required=True),
            TemplateField(key="enrichment_detail", label="不当得利事实", placeholder="如：甲方于XX日误转XX元至乙方账户", required=True),
            TemplateField(key="amount", label="返还金额（元）", placeholder="如：50,000", required=True),
            TemplateField(key="return_method", label="返还方式", placeholder="如：乙方于XX日前转账至甲方账户", required=True),
            TemplateField(key="return_deadline", label="返还期限", placeholder="如：协议签订后7日内", required=True),
            TemplateField(key="breach_clause", label="违约条款特别约定", placeholder="如需特别约定", required=False),
        ],
        outline_sections=["协议主体", "不当得利事实", "返还金额", "返还方式与期限", "利息处理", "违约责任", "争议解决", "其他约定"],
        prompt_template="请生成一份不当得利返还协议，甲方为受损方{party_a}，乙方为得利方{party_b}，事实{enrichment_detail}，返还金额{amount}元，方式{return_method}，期限{return_deadline}。",
        law_references=["《中华人民共和国民法典》第985-988条"],
    ),
}


def get_all_categories() -> List[Dict[str, Any]]:
    result = []
    for cat in CONTRACT_CATEGORIES:
        cat_dict = {
            "id": cat.id,
            "name": cat.name,
            "description": cat.description,
            "icon": cat.icon,
            "color": cat.color,
            "subcategories": [],
            "template_count": 0,
        }
        for sub in cat.subcategories:
            templates_summary = []
            for tid in sub.template_ids:
                t = CONTRACT_TEMPLATES.get(tid)
                if t:
                    templates_summary.append({
                        "id": t.id,
                        "name": t.name,
                        "description": t.description,
                        "field_count": len(t.fields),
                    })
            sub_dict = {
                "id": sub.id,
                "name": sub.name,
                "description": sub.description,
                "icon": sub.icon,
                "template_ids": sub.template_ids,
                "template_count": len(sub.template_ids),
                "templates": templates_summary,
            }
            cat_dict["subcategories"].append(sub_dict)
            cat_dict["template_count"] += len(sub.template_ids)
        result.append(cat_dict)
    return result


def get_template_by_id(template_id: str) -> Optional[ContractTemplate]:
    return CONTRACT_TEMPLATES.get(template_id)


def get_templates_by_subcategory(subcategory_id: str) -> List[ContractTemplate]:
    return [t for t in CONTRACT_TEMPLATES.values() if t.subcategory_id == subcategory_id]


def search_templates(keyword: str) -> List[ContractTemplate]:
    keyword_lower = keyword.lower()
    results = []
    for t in CONTRACT_TEMPLATES.values():
        if (keyword_lower in t.name.lower() or
            keyword_lower in t.description.lower() or
            keyword_lower in t.category_id.lower() or
            any(keyword_lower in f.label.lower() for f in t.fields)):
            results.append(t)
    return results


def template_to_dict(t: ContractTemplate) -> Dict[str, Any]:
    return {
        "id": t.id,
        "name": t.name,
        "description": t.description,
        "category_id": t.category_id,
        "subcategory_id": t.subcategory_id,
        "fields": [
            {
                "key": f.key,
                "label": f.label,
                "field_type": f.field_type,
                "required": f.required,
                "placeholder": f.placeholder,
                "options": f.options,
                "default_value": f.default_value,
            }
            for f in t.fields
        ],
        "outline_sections": t.outline_sections,
        "prompt_template": t.prompt_template,
        "law_references": t.law_references,
    }
