from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field


@dataclass
class DocTemplateField:
    key: str
    label: str
    field_type: str = "text"
    required: bool = True
    placeholder: str = ""
    options: List[str] = field(default_factory=list)
    default_value: str = ""


@dataclass
class DocTemplate:
    id: str
    name: str
    description: str
    category_id: str
    fields: List[DocTemplateField]
    outline_sections: List[str]
    prompt_template: str
    law_references: List[str] = field(default_factory=list)


@dataclass
class DocCategory:
    id: str
    name: str
    description: str
    icon: str
    color: str
    template_ids: List[str]


DOC_CATEGORIES: List[DocCategory] = [
    DocCategory(
        id="litigation",
        name="民事纠纷类诉讼文书",
        description="打官司必备文书。涵盖民事起诉状、答辩状、上诉状、执行申请书等诉讼程序文书，助您依法维权。",
        icon="ph-scales",
        color="bg-red-500",
        template_ids=["lit_civil_complaint", "lit_civil_defense", "lit_appeal", "lit_execution_apply", "lit_property_preservation", "lit_jurisdiction_objection"],
    ),
    DocCategory(
        id="labor_arb",
        name="劳动争议类",
        description="劳动者维权利器。涵盖劳动仲裁申请书、答辩书、解除劳动合同通知书、工资催告函等劳动争议文书。",
        icon="ph-users",
        color="bg-teal-500",
        template_ids=["arb_labor_apply", "arb_labor_defense", "labor_contract_terminate", "labor_wage_demand"],
    ),
    DocCategory(
        id="marriage_family",
        name="婚姻家事类",
        description="家事法律文书。涵盖离婚起诉状、离婚协议书、抚养权变更起诉状、抚养费起诉状等婚姻家庭类文书。",
        icon="ph-heart",
        color="bg-pink-500",
        template_ids=["mf_divorce_complaint", "mf_divorce_agreement", "mf_custody_change", "mf_support_complaint"],
    ),
    DocCategory(
        id="inheritance",
        name="继承类",
        description="遗产继承文书。涵盖遗嘱（自书/代书）、遗产继承起诉状等继承类法律文书，保障遗产依法分配。",
        icon="ph-scroll",
        color="bg-amber-500",
        template_ids=["inh_will", "inh_inheritance_complaint"],
    ),
    DocCategory(
        id="debt_dispute",
        name="债务纠纷类",
        description="讨债维权文书。涵盖民间借贷起诉状、催款函/律师函、支付令申请书、借条/欠条等债务纠纷文书。",
        icon="ph-money",
        color="bg-orange-500",
        template_ids=["debt_loan_complaint", "debt_demand_letter", "debt_payment_order", "debt_iou"],
    ),
    DocCategory(
        id="daily_general",
        name="日常通用类",
        description="日常法律文书。涵盖授权委托书、声明书、承诺书、情况说明、投诉信、举报信等常用法律文书。",
        icon="ph-file-text",
        color="bg-blue-500",
        template_ids=["gen_authorization", "gen_declaration", "gen_commitment", "gen_explanation", "gen_complaint_letter", "gen_report_letter"],
    ),
    DocCategory(
        id="lawyer_docs",
        name="律师专用文书",
        description="律师执业文书。涵盖律师函、法律意见书、尽职调查报告、法律顾问合同、委托代理合同、风险告知书、案件分析报告、结案报告等专业文书。",
        icon="ph-briefcase",
        color="bg-indigo-500",
        template_ids=["law_lawyer_letter", "law_legal_opinion", "law_due_diligence", "law_advisor_contract", "law_agency_contract", "law_risk_notice", "law_case_analysis", "law_closing_report"],
    ),
    DocCategory(
        id="arbitration",
        name="仲裁文书",
        description="商事仲裁文书。涵盖仲裁申请书、答辩书、反请求书、代理词、撤销仲裁裁决申请书、申请执行仲裁裁决书等仲裁程序文书。",
        icon="ph-gavel",
        color="bg-purple-500",
        template_ids=["arb_apply", "arb_defense", "arb_counterclaim", "arb_representation", "arb_cancel_apply", "arb_enforcement_apply"],
    ),
]


DOC_TEMPLATES: Dict[str, DocTemplate] = {
    "lit_civil_complaint": DocTemplate(
        id="lit_civil_complaint",
        name="民事起诉状",
        description="打官司第一步。用于向法院提起民事诉讼，明确诉讼请求与事实理由。",
        category_id="litigation",
        fields=[
            DocTemplateField(key="plaintiff", label="原告", placeholder="原告姓名/名称", required=True),
            DocTemplateField(key="plaintiff_id", label="原告身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="plaintiff_address", label="原告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="plaintiff_phone", label="原告联系电话", placeholder="如：138XXXXXXXX", required=True),
            DocTemplateField(key="defendant", label="被告", placeholder="被告姓名/名称", required=True),
            DocTemplateField(key="defendant_id", label="被告身份证号/统一社会信用代码", placeholder="如已知请填写", required=False),
            DocTemplateField(key="defendant_address", label="被告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="defendant_phone", label="被告联系电话", placeholder="如已知请填写", required=False),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="claims", label="诉讼请求", placeholder="如：1.判令被告偿还借款本金XX元及利息...", required=True),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述纠纷经过及法律依据", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据清单", placeholder="如：1.借款合同 2.转账记录 3.微信聊天记录", required=False, field_type="textarea"),
        ],
        outline_sections=["当事人信息", "诉讼请求", "事实与理由", "证据清单", "此致法院", "签署栏"],
        prompt_template="请生成一份民事起诉状，原告{plaintiff}，被告{defendant}，向{court}提起诉讼。诉讼请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国民事诉讼法》", "《中华人民共和国民法典》"],
    ),
    "lit_civil_defense": DocTemplate(
        id="lit_civil_defense",
        name="民事答辩状",
        description="被告维权利器。针对民事起诉状提出答辩，逐条反驳原告诉讼请求与理由。",
        category_id="litigation",
        fields=[
            DocTemplateField(key="defendant", label="答辩人（被告）", placeholder="答辩人姓名/名称", required=True),
            DocTemplateField(key="defendant_id", label="答辩人身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="defendant_address", label="答辩人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="plaintiff", label="被答辩人（原告）", placeholder="原告姓名/名称", required=True),
            DocTemplateField(key="case_no", label="案号", placeholder="如：（2025）京0105民初XXXX号", required=True),
            DocTemplateField(key="court", label="审理法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="defense_opinion", label="答辩意见", placeholder="逐条反驳原告的诉讼请求及理由", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="答辩证据", placeholder="支持答辩意见的证据", required=False, field_type="textarea"),
        ],
        outline_sections=["答辩人信息", "案由", "答辩意见", "答辩证据", "此致法院", "签署栏"],
        prompt_template="请生成一份民事答辩状，答辩人{defendant}，被答辩人{plaintiff}，案号{case_no}，审理法院{court}。答辩意见：{defense_opinion}。",
        law_references=["《中华人民共和国民事诉讼法》"],
    ),
    "lit_appeal": DocTemplate(
        id="lit_appeal",
        name="上诉状",
        description="不服一审判决？依法上诉。向上一级法院提起上诉，争取改判或发回重审。",
        category_id="litigation",
        fields=[
            DocTemplateField(key="appellant", label="上诉人", placeholder="上诉人姓名/名称", required=True),
            DocTemplateField(key="appellant_id", label="上诉人身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="appellant_address", label="上诉人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="appellee", label="被上诉人", placeholder="被上诉人姓名/名称", required=True),
            DocTemplateField(key="appellee_address", label="被上诉人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="original_case_no", label="一审案号", placeholder="如：（2025）京0105民初XXXX号", required=True),
            DocTemplateField(key="original_court", label="一审法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="appeal_court", label="上诉法院", placeholder="如：北京市第三中级人民法院", required=True),
            DocTemplateField(key="appeal_claims", label="上诉请求", placeholder="如：1.撤销一审判决 2.改判...", required=True),
            DocTemplateField(key="appeal_reasons", label="上诉理由", placeholder="详细阐述不服一审判决的理由", required=True, field_type="textarea"),
        ],
        outline_sections=["上诉人信息", "被上诉人信息", "一审情况", "上诉请求", "上诉理由", "此致法院", "签署栏"],
        prompt_template="请生成一份上诉状，上诉人{appellant}，被上诉人{appellee}，一审案号{original_case_no}，一审法院{original_court}，上诉至{appeal_court}。上诉请求：{appeal_claims}。上诉理由：{appeal_reasons}。",
        law_references=["《中华人民共和国民事诉讼法》第164-168条"],
    ),
    "lit_execution_apply": DocTemplate(
        id="lit_execution_apply",
        name="执行申请书",
        description="判决生效对方不履行？申请强制执行。向法院申请查封、扣押、冻结被执行人财产。",
        category_id="litigation",
        fields=[
            DocTemplateField(key="applicant", label="申请执行人", placeholder="申请人姓名/名称", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="respondent", label="被执行人", placeholder="被执行人姓名/名称", required=True),
            DocTemplateField(key="respondent_id", label="被执行人身份证号/统一社会信用代码", placeholder="如已知请填写", required=False),
            DocTemplateField(key="respondent_address", label="被执行人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="执行法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="case_no", label="原审案号", placeholder="如：（2025）京0105民初XXXX号", required=True),
            DocTemplateField(key="judgment_content", label="判决/裁定内容", placeholder="简述生效判决确定的内容", required=True, field_type="textarea"),
            DocTemplateField(key="execution_claims", label="申请执行事项", placeholder="如：1.强制被执行人偿还XX元 2.加倍支付迟延履行期间的债务利息", required=True, field_type="textarea"),
            DocTemplateField(key="property_clue", label="可供执行财产线索", placeholder="如已知请填写", required=False, field_type="textarea"),
        ],
        outline_sections=["申请执行人信息", "被执行人信息", "执行依据", "申请执行事项", "财产线索", "此致法院", "签署栏"],
        prompt_template="请生成一份执行申请书，申请执行人{applicant}，被执行人{respondent}，执行法院{court}，原审案号{case_no}。判决内容：{judgment_content}。申请执行事项：{execution_claims}。",
        law_references=["《中华人民共和国民事诉讼法》执行程序编"],
    ),
    "lit_property_preservation": DocTemplate(
        id="lit_property_preservation",
        name="财产保全申请书",
        description="防止对方转移财产。在诉前或诉讼中申请查封、扣押、冻结对方财产，保障判决可执行。",
        category_id="litigation",
        fields=[
            DocTemplateField(key="applicant", label="申请人", placeholder="申请人姓名/名称", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="respondent", label="被申请人", placeholder="被申请人姓名/名称", required=True),
            DocTemplateField(key="respondent_address", label="被申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="preservation_type", label="保全类型", placeholder="如：诉前财产保全/诉讼财产保全", required=True),
            DocTemplateField(key="preservation_target", label="保全标的", placeholder="如：被申请人名下位于XX的房产/银行存款XX元", required=True),
            DocTemplateField(key="preservation_amount", label="保全金额（元）", placeholder="如：1,000,000", required=True),
            DocTemplateField(key="reasons", label="申请理由", placeholder="说明为何需要采取保全措施", required=True, field_type="textarea"),
            DocTemplateField(key="guarantee", label="担保情况", placeholder="如：申请人提供XX万元现金担保", required=True),
        ],
        outline_sections=["申请人信息", "被申请人信息", "保全请求", "申请理由", "担保情况", "此致法院", "签署栏"],
        prompt_template="请生成一份财产保全申请书，申请人{applicant}，被申请人{respondent}，管辖法院{court}，保全类型{preservation_type}，保全标的{preservation_target}，保全金额{preservation_amount}元。申请理由：{reasons}。",
        law_references=["《中华人民共和国民事诉讼法》第100-105条"],
    ),
    "lit_jurisdiction_objection": DocTemplate(
        id="lit_jurisdiction_objection",
        name="管辖权异议申请书",
        description="管辖权有误？及时异议。对受理法院的管辖权提出异议，争取移送至有管辖权的法院审理。",
        category_id="litigation",
        fields=[
            DocTemplateField(key="applicant", label="申请人（被告）", placeholder="申请人姓名/名称", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="plaintiff", label="被申请人（原告）", placeholder="原告姓名/名称", required=True),
            DocTemplateField(key="case_no", label="案号", placeholder="如：（2025）京0105民初XXXX号", required=True),
            DocTemplateField(key="current_court", label="现受理法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="suggested_court", label="建议移送法院", placeholder="如：北京市海淀区人民法院", required=True),
            DocTemplateField(key="objection_reasons", label="异议理由", placeholder="详细说明为何该法院无管辖权", required=True, field_type="textarea"),
        ],
        outline_sections=["申请人信息", "案由", "异议请求", "异议理由", "此致法院", "签署栏"],
        prompt_template="请生成一份管辖权异议申请书，申请人{applicant}，案号{case_no}，现受理法院{current_court}，建议移送至{suggested_court}。异议理由：{objection_reasons}。",
        law_references=["《中华人民共和国民事诉讼法》第127条"],
    ),
    "arb_labor_apply": DocTemplate(
        id="arb_labor_apply",
        name="劳动仲裁申请书",
        description="劳动维权第一步。向劳动人事争议仲裁委员会申请仲裁，主张合法权益。",
        category_id="labor_arb",
        fields=[
            DocTemplateField(key="applicant", label="申请人（劳动者）", placeholder="申请人姓名", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="applicant_phone", label="申请人联系电话", placeholder="如：138XXXXXXXX", required=True),
            DocTemplateField(key="respondent", label="被申请人（用人单位）", placeholder="公司全称", required=True),
            DocTemplateField(key="respondent_address", label="被申请人住所地", placeholder="公司注册地址", required=True),
            DocTemplateField(key="respondent_legal", label="被申请人法定代表人", placeholder="如：张三", required=False),
            DocTemplateField(key="arb_committee", label="仲裁委员会", placeholder="如：北京市朝阳区劳动人事争议仲裁委员会", required=True),
            DocTemplateField(key="entry_date", label="入职日期", placeholder="如：2020年3月1日", required=True),
            DocTemplateField(key="exit_date", label="离职日期", placeholder="如：2025年4月1日", required=True),
            DocTemplateField(key="claims", label="仲裁请求", placeholder="如：1.支付违法解除劳动合同赔偿金XX元 2.支付拖欠工资XX元", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述劳动争议经过", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据清单", placeholder="如：1.劳动合同 2.工资流水 3.解除通知书", required=False, field_type="textarea"),
        ],
        outline_sections=["申请人信息", "被申请人信息", "仲裁请求", "事实与理由", "证据清单", "此致仲裁委员会", "签署栏"],
        prompt_template="请生成一份劳动仲裁申请书，申请人{applicant}，被申请人{respondent}，仲裁委员会{arb_committee}，入职{entry_date}，离职{exit_date}。仲裁请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国劳动法》", "《中华人民共和国劳动合同法》", "《中华人民共和国劳动争议调解仲裁法》"],
    ),
    "arb_labor_defense": DocTemplate(
        id="arb_labor_defense",
        name="劳动仲裁答辩书",
        description="用人单位应诉必备。针对劳动仲裁申请提出答辩，维护用人单位合法权益。",
        category_id="labor_arb",
        fields=[
            DocTemplateField(key="respondent", label="答辩人（用人单位）", placeholder="公司全称", required=True),
            DocTemplateField(key="respondent_address", label="答辩人住所地", placeholder="公司注册地址", required=True),
            DocTemplateField(key="respondent_legal", label="法定代表人", placeholder="如：张三", required=True),
            DocTemplateField(key="applicant", label="被答辩人（劳动者）", placeholder="劳动者姓名", required=True),
            DocTemplateField(key="arb_committee", label="仲裁委员会", placeholder="如：北京市朝阳区劳动人事争议仲裁委员会", required=True),
            DocTemplateField(key="case_no", label="案号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="defense_opinion", label="答辩意见", placeholder="逐条反驳申请人的仲裁请求", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="答辩证据", placeholder="支持答辩意见的证据", required=False, field_type="textarea"),
        ],
        outline_sections=["答辩人信息", "被答辩人信息", "答辩意见", "答辩证据", "此致仲裁委员会", "签署栏"],
        prompt_template="请生成一份劳动仲裁答辩书，答辩人{respondent}，被答辩人{applicant}，仲裁委员会{arb_committee}。答辩意见：{defense_opinion}。",
        law_references=["《中华人民共和国劳动合同法》", "《中华人民共和国劳动争议调解仲裁法》"],
    ),
    "labor_contract_terminate": DocTemplate(
        id="labor_contract_terminate",
        name="解除劳动合同通知书",
        description="解除劳动关系正式通知。用人单位或劳动者依法单方解除劳动合同的书面通知。",
        category_id="labor_arb",
        fields=[
            DocTemplateField(key="sender", label="通知方", placeholder="通知方姓名/公司名称", required=True),
            DocTemplateField(key="receiver", label="被通知方", placeholder="被通知方姓名/公司名称", required=True),
            DocTemplateField(key="receiver_position", label="被通知方岗位", placeholder="如：销售经理", required=True),
            DocTemplateField(key="entry_date", label="入职日期", placeholder="如：2020年3月1日", required=True),
            DocTemplateField(key="terminate_date", label="解除日期", placeholder="如：2025年5月1日", required=True),
            DocTemplateField(key="terminate_reason", label="解除原因", placeholder="如：协商一致/严重违反规章制度/经济性裁员等", required=True),
            DocTemplateField(key="legal_basis", label="法律依据", placeholder="如：《劳动合同法》第XX条", required=True),
            DocTemplateField(key="handover", label="工作交接要求", placeholder="如：请于解除日前完成工作交接", required=False),
            DocTemplateField(key="compensation", label="经济补偿", placeholder="如：支付N+1个月经济补偿金XX元", required=False),
        ],
        outline_sections=["通知方信息", "被通知方信息", "解除原因", "法律依据", "解除日期", "工作交接", "经济补偿", "签署栏"],
        prompt_template="请生成一份解除劳动合同通知书，通知方{sender}，被通知方{receiver}，岗位{receiver_position}，入职{entry_date}，解除日期{terminate_date}，解除原因{terminate_reason}，法律依据{legal_basis}。",
        law_references=["《中华人民共和国劳动合同法》第36-50条"],
    ),
    "labor_wage_demand": DocTemplate(
        id="labor_wage_demand",
        name="工资催告函",
        description="欠薪催讨正式函件。催促用人单位支付拖欠工资，逾期将采取法律措施。",
        category_id="labor_arb",
        fields=[
            DocTemplateField(key="sender", label="催告人（劳动者）", placeholder="劳动者姓名", required=True),
            DocTemplateField(key="sender_id", label="催告人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="receiver", label="被催告人（用人单位）", placeholder="公司全称", required=True),
            DocTemplateField(key="receiver_address", label="被催告人地址", placeholder="公司注册地址", required=True),
            DocTemplateField(key="position", label="岗位", placeholder="如：软件工程师", required=True),
            DocTemplateField(key="entry_date", label="入职日期", placeholder="如：2023年1月1日", required=True),
            DocTemplateField(key="arrears_period", label="欠薪期间", placeholder="如：2025年1月至2025年3月", required=True),
            DocTemplateField(key="arrears_amount", label="欠薪金额（元）", placeholder="如：45,000", required=True),
            DocTemplateField(key="deadline", label="催告期限", placeholder="如：收到本函后5个工作日内", required=True),
            DocTemplateField(key="further_action", label="逾期后续措施", placeholder="如：将向劳动监察部门投诉/申请劳动仲裁", required=False),
        ],
        outline_sections=["催告人信息", "被催告人信息", "欠薪事实", "催告要求", "逾期后果", "签署栏"],
        prompt_template="请生成一份工资催告函，催告人{sender}，被催告人{receiver}，岗位{position}，欠薪期间{arrears_period}，欠薪金额{arrears_amount}元，催告期限{deadline}。",
        law_references=["《中华人民共和国劳动法》第50条", "《中华人民共和国劳动合同法》第30条", "《保障农民工工资支付条例》"],
    ),
    "mf_divorce_complaint": DocTemplate(
        id="mf_divorce_complaint",
        name="离婚起诉状",
        description="诉讼离婚必备文书。向法院提起离婚诉讼，明确离婚请求、子女抚养及财产分割方案。",
        category_id="marriage_family",
        fields=[
            DocTemplateField(key="plaintiff", label="原告", placeholder="原告姓名", required=True),
            DocTemplateField(key="plaintiff_gender", label="原告性别", placeholder="男/女", required=True),
            DocTemplateField(key="plaintiff_id", label="原告身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="plaintiff_address", label="原告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="defendant", label="被告", placeholder="被告姓名", required=True),
            DocTemplateField(key="defendant_gender", label="被告性别", placeholder="男/女", required=True),
            DocTemplateField(key="defendant_id", label="被告身份证号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="defendant_address", label="被告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="marriage_date", label="结婚日期", placeholder="如：2015年6月1日", required=True),
            DocTemplateField(key="marriage_cert", label="结婚证号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="has_children", label="是否有子女", placeholder="有/无", required=True),
            DocTemplateField(key="children_info", label="子女信息", placeholder="如：长子张XX，2016年出生", required=False),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="claims", label="诉讼请求", placeholder="如：1.判决离婚 2.婚生子由原告抚养 3.依法分割夫妻共同财产", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述婚姻状况及离婚理由", required=True, field_type="textarea"),
        ],
        outline_sections=["原告信息", "被告信息", "婚姻概况", "诉讼请求", "事实与理由", "此致法院", "签署栏"],
        prompt_template="请生成一份离婚起诉状，原告{plaintiff}，被告{defendant}，结婚日期{marriage_date}，管辖法院{court}。诉讼请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国民法典》婚姻家庭编", "《中华人民共和国民事诉讼法》"],
    ),
    "mf_divorce_agreement": DocTemplate(
        id="mf_divorce_agreement",
        name="离婚协议书",
        description="协议离婚核心文书。双方自愿离婚，约定子女抚养、财产分割、债务处理等事项。",
        category_id="marriage_family",
        fields=[
            DocTemplateField(key="party_a", label="男方", placeholder="男方姓名", required=True),
            DocTemplateField(key="party_a_id", label="男方身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="party_b", label="女方", placeholder="女方姓名", required=True),
            DocTemplateField(key="party_b_id", label="女方身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="marriage_date", label="结婚日期", placeholder="如：2015年6月1日", required=True),
            DocTemplateField(key="marriage_cert", label="结婚证号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="has_children", label="是否有子女", placeholder="有/无", required=True),
            DocTemplateField(key="children_info", label="子女信息及抚养安排", placeholder="如：婚生子张XX由男方抚养，女方每月支付抚养费2000元", required=False, field_type="textarea"),
            DocTemplateField(key="property_division", label="财产分割", placeholder="如：位于XX的房产归男方所有，男方补偿女方XX元", required=True, field_type="textarea"),
            DocTemplateField(key="debt_handling", label="债务处理", placeholder="如：各自名下债务各自承担", required=False, field_type="textarea"),
        ],
        outline_sections=["双方信息", "自愿离婚", "子女抚养", "财产分割", "债务处理", "其他约定", "签署栏"],
        prompt_template="请生成一份离婚协议书，男方{party_a}，女方{party_b}，结婚日期{marriage_date}。子女抚养：{children_info}。财产分割：{property_division}。债务处理：{debt_handling}。",
        law_references=["《中华人民共和国民法典》第1076条", "《婚姻登记条例》"],
    ),
    "mf_custody_change": DocTemplate(
        id="mf_custody_change",
        name="抚养权变更起诉状",
        description="变更抚养权有理有据。向法院起诉变更子女抚养权，保障子女健康成长。",
        category_id="marriage_family",
        fields=[
            DocTemplateField(key="plaintiff", label="原告（要求变更方）", placeholder="原告姓名", required=True),
            DocTemplateField(key="plaintiff_id", label="原告身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="plaintiff_address", label="原告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="defendant", label="被告（现抚养方）", placeholder="被告姓名", required=True),
            DocTemplateField(key="defendant_address", label="被告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="child_name", label="子女姓名", placeholder="子女姓名", required=True),
            DocTemplateField(key="child_age", label="子女年龄", placeholder="如：8岁", required=True),
            DocTemplateField(key="current_custody", label="现抚养情况", placeholder="如：子女目前随被告生活", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="claims", label="诉讼请求", placeholder="如：1.变更婚生子抚养权归原告 2.被告每月支付抚养费XX元", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细说明变更抚养权的理由", required=True, field_type="textarea"),
        ],
        outline_sections=["原告信息", "被告信息", "子女信息", "诉讼请求", "事实与理由", "此致法院", "签署栏"],
        prompt_template="请生成一份抚养权变更起诉状，原告{plaintiff}，被告{defendant}，子女{child_name}（{child_age}岁），管辖法院{court}。诉讼请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国民法典》婚姻家庭编", "《最高人民法院关于适用〈民法典〉婚姻家庭编的解释（一）》第56条"],
    ),
    "mf_support_complaint": DocTemplate(
        id="mf_support_complaint",
        name="抚养费起诉状",
        description="为孩子争取抚养费。向法院起诉要求对方支付或增加子女抚养费，保障子女生活教育需要。",
        category_id="marriage_family",
        fields=[
            DocTemplateField(key="plaintiff", label="原告（法定代理人）", placeholder="原告姓名", required=True),
            DocTemplateField(key="plaintiff_id", label="原告身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="child_name", label="子女姓名", placeholder="子女姓名", required=True),
            DocTemplateField(key="child_age", label="子女年龄", placeholder="如：8岁", required=True),
            DocTemplateField(key="defendant", label="被告（应支付抚养费方）", placeholder="被告姓名", required=True),
            DocTemplateField(key="defendant_address", label="被告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="current_support", label="现抚养费情况", placeholder="如：目前每月支付1000元/从未支付", required=True),
            DocTemplateField(key="requested_support", label="请求抚养费金额（元/月）", placeholder="如：3,000", required=True),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细说明请求抚养费的理由", required=True, field_type="textarea"),
        ],
        outline_sections=["原告信息", "被告信息", "子女信息", "诉讼请求", "事实与理由", "此致法院", "签署栏"],
        prompt_template="请生成一份抚养费起诉状，原告{plaintiff}，被告{defendant}，子女{child_name}（{child_age}岁），管辖法院{court}，请求抚养费{requested_support}元/月。事实与理由：{facts}。",
        law_references=["《中华人民共和国民法典》第1067条、第1085条"],
    ),
    "inh_will": DocTemplate(
        id="inh_will",
        name="遗嘱（自书/代书）",
        description="身后事早安排。自书或代书遗嘱，明确遗产分配意愿，避免继承纠纷。",
        category_id="inheritance",
        fields=[
            DocTemplateField(key="testator", label="立遗嘱人", placeholder="立遗嘱人姓名", required=True),
            DocTemplateField(key="testator_id", label="立遗嘱人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="testator_address", label="立遗嘱人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="will_type", label="遗嘱类型", placeholder="如：自书遗嘱/代书遗嘱", required=True),
            DocTemplateField(key="mental_status", label="精神状况声明", placeholder="如：立遗嘱时神志清醒，具有完全民事行为能力", required=True),
            DocTemplateField(key="property_list", label="遗产清单及分配方案", placeholder="如：1.位于XX的房产由长子继承 2.XX银行存款由女儿继承", required=True, field_type="textarea"),
            DocTemplateField(key="executor", label="遗嘱执行人", placeholder="如：张XX（身份证号：XXX）", required=False),
            DocTemplateField(key="special_instructions", label="特别说明", placeholder="如：其他特别交代事项", required=False, field_type="textarea"),
            DocTemplateField(key="witness_a", label="见证人一（代书遗嘱需填写）", placeholder="如：李XX，身份证号：XXX", required=False),
            DocTemplateField(key="witness_b", label="见证人二（代书遗嘱需填写）", placeholder="如：王XX，身份证号：XXX", required=False),
        ],
        outline_sections=["立遗嘱人信息", "精神状况声明", "遗产清单及分配", "遗嘱执行人", "特别说明", "见证人信息", "签署栏"],
        prompt_template="请生成一份{will_type}，立遗嘱人{testator}，身份证号{testator_id}。遗产分配方案：{property_list}。遗嘱执行人：{executor}。",
        law_references=["《中华人民共和国民法典》继承编第1134-1140条"],
    ),
    "inh_inheritance_complaint": DocTemplate(
        id="inh_inheritance_complaint",
        name="遗产继承起诉状",
        description="遗产被侵占？依法起诉。因遗产继承纠纷向法院提起诉讼，维护合法继承权。",
        category_id="inheritance",
        fields=[
            DocTemplateField(key="plaintiff", label="原告", placeholder="原告姓名", required=True),
            DocTemplateField(key="plaintiff_id", label="原告身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="plaintiff_address", label="原告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="plaintiff_relation", label="原告与被继承人关系", placeholder="如：长子/配偶", required=True),
            DocTemplateField(key="defendant", label="被告", placeholder="被告姓名", required=True),
            DocTemplateField(key="defendant_relation", label="被告与被继承人关系", placeholder="如：次子/兄弟姐妹", required=True),
            DocTemplateField(key="defendant_address", label="被告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="deceased", label="被继承人", placeholder="被继承人姓名", required=True),
            DocTemplateField(key="death_date", label="死亡日期", placeholder="如：2024年12月1日", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="claims", label="诉讼请求", placeholder="如：1.依法分割被继承人遗产 2.判令被告返还侵占的遗产", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述继承纠纷经过", required=True, field_type="textarea"),
        ],
        outline_sections=["原告信息", "被告信息", "被继承人信息", "诉讼请求", "事实与理由", "此致法院", "签署栏"],
        prompt_template="请生成一份遗产继承起诉状，原告{plaintiff}（{plaintiff_relation}），被告{defendant}（{defendant_relation}），被继承人{deceased}，死亡日期{death_date}，管辖法院{court}。诉讼请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国民法典》继承编"],
    ),
    "debt_loan_complaint": DocTemplate(
        id="debt_loan_complaint",
        name="民间借贷起诉状",
        description="借款不还？法院见。因民间借贷纠纷向法院提起诉讼，追讨借款本金及利息。",
        category_id="debt_dispute",
        fields=[
            DocTemplateField(key="plaintiff", label="原告（出借人）", placeholder="原告姓名/名称", required=True),
            DocTemplateField(key="plaintiff_id", label="原告身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="plaintiff_address", label="原告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="defendant", label="被告（借款人）", placeholder="被告姓名/名称", required=True),
            DocTemplateField(key="defendant_id", label="被告身份证号/统一社会信用代码", placeholder="如已知请填写", required=False),
            DocTemplateField(key="defendant_address", label="被告住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="loan_amount", label="借款本金（元）", placeholder="如：100,000", required=True),
            DocTemplateField(key="loan_date", label="借款日期", placeholder="如：2023年6月1日", required=True),
            DocTemplateField(key="repayment_date", label="约定还款日期", placeholder="如：2024年6月1日", required=True),
            DocTemplateField(key="interest_rate", label="约定利率", placeholder="如：年利率6%/未约定", required=True),
            DocTemplateField(key="claims", label="诉讼请求", placeholder="如：1.偿还借款本金XX元 2.支付利息XX元 3.承担诉讼费用", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述借贷经过及违约情况", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据清单", placeholder="如：1.借条 2.转账记录 3.微信聊天记录", required=False, field_type="textarea"),
        ],
        outline_sections=["原告信息", "被告信息", "诉讼请求", "事实与理由", "证据清单", "此致法院", "签署栏"],
        prompt_template="请生成一份民间借贷起诉状，原告{plaintiff}，被告{defendant}，管辖法院{court}，借款本金{loan_amount}元，借款日期{loan_date}，约定还款{repayment_date}，利率{interest_rate}。诉讼请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国民法典》合同编借款合同章", "《最高人民法院关于审理民间借贷案件适用法律若干问题的规定》"],
    ),
    "debt_demand_letter": DocTemplate(
        id="debt_demand_letter",
        name="催款函/律师函",
        description="正式催款函件。催促债务人还款，明确逾期法律后果，为后续诉讼留存证据。",
        category_id="debt_dispute",
        fields=[
            DocTemplateField(key="sender", label="发函人/债权人", placeholder="发函人姓名/名称", required=True),
            DocTemplateField(key="sender_address", label="发函人地址", placeholder="详细地址", required=True),
            DocTemplateField(key="receiver", label="收函人/债务人", placeholder="收函人姓名/名称", required=True),
            DocTemplateField(key="receiver_address", label="收函人地址", placeholder="详细地址", required=True),
            DocTemplateField(key="debt_amount", label="欠款金额（元）", placeholder="如：100,000", required=True),
            DocTemplateField(key="debt_origin", label="欠款事由", placeholder="如：2023年6月1日借款/货款", required=True),
            DocTemplateField(key="deadline", label="催告期限", placeholder="如：收到本函后7日内", required=True),
            DocTemplateField(key="consequences", label="逾期后果", placeholder="如：将向法院提起诉讼/申请支付令", required=False),
        ],
        outline_sections=["发函人信息", "收函人信息", "欠款事实", "催告要求", "逾期后果", "签署栏"],
        prompt_template="请生成一份催款函，发函人{sender}，收函人{receiver}，欠款金额{debt_amount}元，欠款事由{debt_origin}，催告期限{deadline}。",
        law_references=["《中华人民共和国民法典》合同编"],
    ),
    "debt_payment_order": DocTemplate(
        id="debt_payment_order",
        name="支付令申请书",
        description="债权明确？申请支付令。向法院申请支付令，快速实现债权，无需经过诉讼程序。",
        category_id="debt_dispute",
        fields=[
            DocTemplateField(key="applicant", label="申请人（债权人）", placeholder="申请人姓名/名称", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号/统一社会信用代码", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="respondent", label="被申请人（债务人）", placeholder="被申请人姓名/名称", required=True),
            DocTemplateField(key="respondent_address", label="被申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市朝阳区人民法院", required=True),
            DocTemplateField(key="debt_amount", label="请求支付金额（元）", placeholder="如：100,000", required=True),
            DocTemplateField(key="debt_origin", label="债权债务关系", placeholder="如：2023年6月1日借款，约定2024年6月1日归还", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据", placeholder="如：借条、转账记录等", required=True, field_type="textarea"),
            DocTemplateField(key="no_other_dispute", label="无其他债务纠纷声明", placeholder="如：申请人与被申请人之间没有其他债务纠纷", required=True),
        ],
        outline_sections=["申请人信息", "被申请人信息", "申请事项", "债权债务关系", "证据", "此致法院", "签署栏"],
        prompt_template="请生成一份支付令申请书，申请人{applicant}，被申请人{respondent}，管辖法院{court}，请求支付金额{debt_amount}元。债权债务关系：{debt_origin}。",
        law_references=["《中华人民共和国民事诉讼法》第214-217条"],
    ),
    "debt_iou": DocTemplate(
        id="debt_iou",
        name="借条/欠条",
        description="借贷凭证规范化。出具合法有效的借条或欠条，明确借贷金额、利率、还款期限等关键要素。",
        category_id="debt_dispute",
        fields=[
            DocTemplateField(key="borrower", label="借款人/欠款人", placeholder="借款人姓名", required=True),
            DocTemplateField(key="borrower_id", label="借款人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="lender", label="出借人/债权人", placeholder="出借人姓名", required=True),
            DocTemplateField(key="lender_id", label="出借人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="amount", label="借款/欠款金额（元）", placeholder="如：100,000", required=True),
            DocTemplateField(key="amount_chinese", label="金额大写", placeholder="如：壹拾万元整", required=True),
            DocTemplateField(key="purpose", label="借款用途", placeholder="如：经营周转/购房", required=True),
            DocTemplateField(key="interest_rate", label="利率", placeholder="如：年利率6%/无息", required=True),
            DocTemplateField(key="repayment_date", label="还款日期", placeholder="如：2025年12月31日", required=True),
            DocTemplateField(key="repayment_method", label="还款方式", placeholder="如：到期一次还本付息", required=True),
            DocTemplateField(key="guarantor", label="担保人", placeholder="如无担保填'无'", required=False),
            DocTemplateField(key="guarantor_id", label="担保人身份证号", placeholder="如无担保可不填", required=False),
        ],
        outline_sections=["借款人信息", "出借人信息", "借款金额", "借款用途", "利率与利息", "还款日期与方式", "担保条款", "签署栏"],
        prompt_template="请生成一份借条，借款人{borrower}，出借人{lender}，借款金额{amount}元（{amount_chinese}），用途{purpose}，利率{interest_rate}，还款日期{repayment_date}，还款方式{repayment_method}。",
        law_references=["《中华人民共和国民法典》合同编借款合同章"],
    ),
    "gen_authorization": DocTemplate(
        id="gen_authorization",
        name="授权委托书",
        description="委托他人办事必备。授权他人代为办理特定事项，明确授权范围与期限。",
        category_id="daily_general",
        fields=[
            DocTemplateField(key="principal", label="委托人", placeholder="委托人姓名", required=True),
            DocTemplateField(key="principal_id", label="委托人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="agent", label="受托人", placeholder="受托人姓名", required=True),
            DocTemplateField(key="agent_id", label="受托人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="entrust_matter", label="委托事项", placeholder="如：代为办理房产过户手续", required=True),
            DocTemplateField(key="authority_scope", label="授权范围", placeholder="如：全权代理/仅限XX事项", required=True),
            DocTemplateField(key="valid_period", label="委托期限", placeholder="如：自2025年1月1日至2025年12月31日", required=True),
            DocTemplateField(key="special_auth", label="特别授权", placeholder="如：代为签署文件/代为收取款项", required=False),
        ],
        outline_sections=["委托人信息", "受托人信息", "委托事项", "授权范围", "委托期限", "特别授权", "委托人承诺", "签署栏"],
        prompt_template="请生成一份授权委托书，委托人{principal}，受托人{agent}，委托事项{entrust_matter}，授权范围{authority_scope}，期限{valid_period}。",
        law_references=["《中华人民共和国民法典》委托代理相关条文"],
    ),
    "gen_declaration": DocTemplate(
        id="gen_declaration",
        name="声明书",
        description="正式声明立场。就特定事项作出正式声明，具有法律效力。",
        category_id="daily_general",
        fields=[
            DocTemplateField(key="declarant", label="声明人", placeholder="声明人姓名", required=True),
            DocTemplateField(key="declarant_id", label="声明人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="declaration_content", label="声明内容", placeholder="详细描述声明事项", required=True, field_type="textarea"),
            DocTemplateField(key="legal_basis", label="法律依据", placeholder="如相关请填写", required=False),
        ],
        outline_sections=["声明人信息", "声明内容", "法律依据", "真实性承诺", "签署栏"],
        prompt_template="请生成一份声明书，声明人{declarant}，声明内容：{declaration_content}。",
        law_references=["《中华人民共和国民法典》"],
    ),
    "gen_commitment": DocTemplate(
        id="gen_commitment",
        name="承诺书",
        description="书面承诺有据可查。就特定事项作出承诺保证，明确违约后果。",
        category_id="daily_general",
        fields=[
            DocTemplateField(key="promisor", label="承诺人", placeholder="承诺人姓名", required=True),
            DocTemplateField(key="promisor_id", label="承诺人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="commitment_to", label="承诺对象", placeholder="如：XX公司/XX部门", required=True),
            DocTemplateField(key="commitment_content", label="承诺内容", placeholder="详细描述承诺事项", required=True, field_type="textarea"),
            DocTemplateField(key="deadline", label="承诺期限", placeholder="如：长期有效/至XX日止", required=False),
            DocTemplateField(key="breach_consequence", label="违约后果", placeholder="如：自愿承担相应法律责任", required=False),
        ],
        outline_sections=["承诺人信息", "承诺对象", "承诺内容", "承诺期限", "违约后果", "签署栏"],
        prompt_template="请生成一份承诺书，承诺人{promisor}，承诺对象{commitment_to}，承诺内容：{commitment_content}。",
        law_references=["《中华人民共和国民法典》"],
    ),
    "gen_explanation": DocTemplate(
        id="gen_explanation",
        name="情况说明",
        description="书面说明事实情况。就特定情况或事实作出书面说明，供相关部门或机构参考。",
        category_id="daily_general",
        fields=[
            DocTemplateField(key="explainer", label="说明人", placeholder="说明人姓名", required=True),
            DocTemplateField(key="explainer_id", label="说明人身份证号", placeholder="如：110101XXXXXXXXXXXX", required=True),
            DocTemplateField(key="explain_to", label="致（接收方）", placeholder="如：XX法院/XX公司/XX部门", required=True),
            DocTemplateField(key="subject", label="说明事项", placeholder="如：关于XX的情况说明", required=True),
            DocTemplateField(key="content", label="情况说明内容", placeholder="详细描述相关情况", required=True, field_type="textarea"),
        ],
        outline_sections=["说明人信息", "致", "说明事项", "情况内容", "真实性承诺", "签署栏"],
        prompt_template="请生成一份情况说明，说明人{explainer}，致{explain_to}，说明事项{subject}，内容：{content}。",
        law_references=["《中华人民共和国民法典》"],
    ),
    "gen_complaint_letter": DocTemplate(
        id="gen_complaint_letter",
        name="投诉信",
        description="维权投诉正式信函。向相关部门投诉举报，陈述事实、表达诉求，维护自身合法权益。",
        category_id="daily_general",
        fields=[
            DocTemplateField(key="complainant", label="投诉人", placeholder="投诉人姓名", required=True),
            DocTemplateField(key="complainant_phone", label="投诉人联系电话", placeholder="如：138XXXXXXXX", required=True),
            DocTemplateField(key="complainant_address", label="投诉人地址", placeholder="详细地址", required=True),
            DocTemplateField(key="complain_to", label="被投诉方", placeholder="被投诉方名称", required=True),
            DocTemplateField(key="complain_to_address", label="被投诉方地址", placeholder="详细地址", required=True),
            DocTemplateField(key="subject", label="投诉事项", placeholder="如：关于XX的投诉", required=True),
            DocTemplateField(key="content", label="投诉内容", placeholder="详细描述投诉事实", required=True, field_type="textarea"),
            DocTemplateField(key="demands", label="投诉诉求", placeholder="如：要求退款/赔偿/道歉等", required=True, field_type="textarea"),
        ],
        outline_sections=["投诉人信息", "被投诉方信息", "投诉事项", "投诉内容", "投诉诉求", "签署栏"],
        prompt_template="请生成一份投诉信，投诉人{complainant}，被投诉方{complain_to}，投诉事项{subject}。投诉内容：{content}。诉求：{demands}。",
        law_references=["《中华人民共和国消费者权益保护法》"],
    ),
    "gen_report_letter": DocTemplate(
        id="gen_report_letter",
        name="举报信",
        description="举报违法行为正式信函。向有关部门举报违法事实，提供线索，维护社会公共利益。",
        category_id="daily_general",
        fields=[
            DocTemplateField(key="reporter", label="举报人", placeholder="举报人姓名（可匿名）", required=True),
            DocTemplateField(key="reporter_phone", label="举报人联系电话", placeholder="如：138XXXXXXXX", required=False),
            DocTemplateField(key="report_to", label="举报对象", placeholder="被举报方名称", required=True),
            DocTemplateField(key="report_to_address", label="举报对象地址", placeholder="详细地址", required=True),
            DocTemplateField(key="authority", label="受理部门", placeholder="如：XX市场监督管理局/XX公安局", required=True),
            DocTemplateField(key="subject", label="举报事项", placeholder="如：关于XX的举报", required=True),
            DocTemplateField(key="content", label="举报内容", placeholder="详细描述违法事实", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据线索", placeholder="如：相关证据材料", required=False, field_type="textarea"),
        ],
        outline_sections=["举报人信息", "举报对象", "受理部门", "举报事项", "举报内容", "证据线索", "签署栏"],
        prompt_template="请生成一份举报信，举报人{reporter}，举报对象{report_to}，受理部门{authority}，举报事项{subject}。举报内容：{content}。",
        law_references=["《中华人民共和国刑事诉讼法》", "《信访工作条例》"],
    ),
    "law_lawyer_letter": DocTemplate(
        id="law_lawyer_letter",
        name="律师函（专业版）",
        description="律师正式法律函件。受委托人委托发出，陈述事实、法律分析及要求，具有法律威慑力。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="承办律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="lawyer_phone", label="律师联系电话", placeholder="如：138XXXXXXXX", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人姓名/名称", required=True),
            DocTemplateField(key="addressee", label="致（收函方）", placeholder="收函方姓名/名称", required=True),
            DocTemplateField(key="addressee_address", label="收函方地址", placeholder="详细地址", required=True),
            DocTemplateField(key="subject", label="函件主题", placeholder="如：关于XX事宜的律师函", required=True),
            DocTemplateField(key="facts", label="事实概述", placeholder="简述相关事实", required=True, field_type="textarea"),
            DocTemplateField(key="legal_analysis", label="法律分析", placeholder="相关法律依据及分析", required=True, field_type="textarea"),
            DocTemplateField(key="demands", label="律师要求", placeholder="如：请在收到本函后X日内...", required=True, field_type="textarea"),
            DocTemplateField(key="deadline", label="回复期限", placeholder="如：收到本函后7日内", required=True),
            DocTemplateField(key="consequences", label="法律后果提示", placeholder="如：逾期将采取法律措施", required=False),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "致收函方", "函件主题", "事实概述", "法律分析", "律师要求", "法律后果", "签署栏"],
        prompt_template="请生成一份律师函，{law_firm}{lawyer}受{client}委托，致{addressee}，主题{subject}。事实：{facts}。法律分析：{legal_analysis}。要求：{demands}。回复期限：{deadline}。",
        law_references=["《中华人民共和国律师法》", "相关实体法"],
    ),
    "law_legal_opinion": DocTemplate(
        id="law_legal_opinion",
        name="法律意见书",
        description="律师专业法律意见。就特定法律问题出具专业分析和结论，为决策提供法律依据。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="出具律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人姓名/名称", required=True),
            DocTemplateField(key="subject", label="法律意见事项", placeholder="如：关于XX事项的法律意见", required=True),
            DocTemplateField(key="background", label="背景事实", placeholder="详细描述相关背景事实", required=True, field_type="textarea"),
            DocTemplateField(key="legal_issues", label="法律问题", placeholder="需要分析的法律问题", required=True, field_type="textarea"),
            DocTemplateField(key="analysis", label="法律分析", placeholder="法律依据及分析", required=True, field_type="textarea"),
            DocTemplateField(key="conclusion", label="法律意见/结论", placeholder="最终法律意见", required=True, field_type="textarea"),
            DocTemplateField(key="disclaimer", label="免责声明", placeholder="如：本意见仅基于委托人提供的信息", required=False),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "意见事项", "背景事实", "法律问题", "法律分析", "法律意见", "免责声明", "签署栏"],
        prompt_template="请生成一份法律意见书，{law_firm}{lawyer}受{client}委托，就{subject}出具法律意见。背景事实：{background}。法律问题：{legal_issues}。法律分析：{analysis}。结论：{conclusion}。",
        law_references=["《中华人民共和国律师法》"],
    ),
    "law_due_diligence": DocTemplate(
        id="law_due_diligence",
        name="尽职调查报告",
        description="投资并购风控利器。律师对目标公司或项目进行法律尽职调查，揭示法律风险并提出建议。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="主办律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人名称", required=True),
            DocTemplateField(key="target_company", label="目标公司", placeholder="目标公司全称", required=True),
            DocTemplateField(key="dd_scope", label="尽调范围", placeholder="如：公司基本信息、股权结构、重大合同、诉讼仲裁、知识产权", required=True, field_type="textarea"),
            DocTemplateField(key="dd_period", label="尽调期间", placeholder="如：2022年1月1日至2024年12月31日", required=True),
            DocTemplateField(key="key_findings", label="主要发现", placeholder="尽调中发现的主要法律问题", required=True, field_type="textarea"),
            DocTemplateField(key="risk_assessment", label="风险评估", placeholder="法律风险等级及说明", required=True, field_type="textarea"),
            DocTemplateField(key="suggestions", label="建议", placeholder="整改建议或风险缓释措施", required=False, field_type="textarea"),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "尽调范围与期间", "目标公司概况", "尽调发现", "风险评估", "建议", "免责声明", "签署栏"],
        prompt_template="请生成一份尽职调查报告，{law_firm}{lawyer}受{client}委托，对{target_company}进行法律尽职调查。尽调范围：{dd_scope}。期间：{dd_period}。主要发现：{key_findings}。风险评估：{risk_assessment}。",
        law_references=["《中华人民共和国公司法》", "《中华人民共和国律师法》"],
    ),
    "law_advisor_contract": DocTemplate(
        id="law_advisor_contract",
        name="法律顾问合同",
        description="聘请法律顾问正式合同。约定律所提供常年法律顾问服务的范围、费用及双方权利义务。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="party_a", label="聘请方（甲方）", placeholder="甲方名称", required=True),
            DocTemplateField(key="party_b", label="受聘方（乙方/律所）", placeholder="律所名称", required=True),
            DocTemplateField(key="lawyer", label="指派律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="service_period", label="服务期限", placeholder="如：自2025年1月1日至2025年12月31日", required=True),
            DocTemplateField(key="service_scope", label="服务范围", placeholder="如：日常法律咨询、合同审查、法律培训等", required=True, field_type="textarea"),
            DocTemplateField(key="annual_fee", label="年度顾问费（元）", placeholder="如：50,000", required=True),
            DocTemplateField(key="payment_method", label="付款方式", placeholder="如：合同签订后10日内支付", required=True),
            DocTemplateField(key="additional_fee", label="额外收费约定", placeholder="如：诉讼代理另行收费", required=False),
        ],
        outline_sections=["合同主体", "服务期限", "服务范围", "顾问费用", "双方权利义务", "保密条款", "合同变更与解除", "违约责任", "争议解决", "签署栏"],
        prompt_template="请生成一份法律顾问合同，甲方{party_a}，乙方{party_b}，指派律师{lawyer}，服务期限{service_period}，顾问费{annual_fee}元。服务范围：{service_scope}。",
        law_references=["《中华人民共和国律师法》"],
    ),
    "law_agency_contract": DocTemplate(
        id="law_agency_contract",
        name="委托代理合同",
        description="委托律师代理正式合同。约定律师代理诉讼或非诉讼事务的范围、授权及费用。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="party_a", label="委托方（甲方）", placeholder="甲方名称", required=True),
            DocTemplateField(key="party_b", label="受托方（乙方/律所）", placeholder="律所名称", required=True),
            DocTemplateField(key="lawyer", label="代理律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="case_name", label="案件/事务名称", placeholder="如：XX诉XX合同纠纷案", required=True),
            DocTemplateField(key="agency_scope", label="代理范围", placeholder="如：一审诉讼/二审诉讼/执行/非诉讼", required=True),
            DocTemplateField(key="authority_type", label="授权类型", placeholder="如：一般授权/特别授权", required=True),
            DocTemplateField(key="agency_fee", label="代理费（元）", placeholder="如：30,000", required=True),
            DocTemplateField(key="fee_method", label="收费方式", placeholder="如：固定收费/风险代理/计时收费", required=True),
            DocTemplateField(key="payment_method", label="付款方式", placeholder="如：合同签订付50%/一审终结付50%", required=True),
            DocTemplateField(key="expenses", label="办案费用承担", placeholder="如：差旅费、鉴定费等由甲方承担", required=False),
        ],
        outline_sections=["合同主体", "委托事项", "代理范围与授权", "代理费用", "付款方式", "甲方权利义务", "乙方权利义务", "合同解除", "违约责任", "争议解决", "签署栏"],
        prompt_template="请生成一份委托代理合同，甲方{party_a}，乙方{party_b}，代理律师{lawyer}，案件{case_name}，代理范围{agency_scope}，授权类型{authority_type}，代理费{agency_fee}元，收费方式{fee_method}。",
        law_references=["《中华人民共和国律师法》", "《律师服务收费管理办法》"],
    ),
    "law_risk_notice": DocTemplate(
        id="law_risk_notice",
        name="风险告知书",
        description="法律风险正式告知。律师向委托人告知案件法律风险，保障委托人知情权与决策权。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="承办律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人姓名/名称", required=True),
            DocTemplateField(key="case_name", label="案件/事务名称", placeholder="如：XX诉XX合同纠纷案", required=True),
            DocTemplateField(key="risk_items", label="风险事项", placeholder="逐条列明可能存在的法律风险", required=True, field_type="textarea"),
            DocTemplateField(key="risk_level", label="风险等级", placeholder="如：高/中/低", required=True),
            DocTemplateField(key="suggestions", label="风险防范建议", placeholder="如：补充证据、和解等", required=False, field_type="textarea"),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "案件/事务", "风险事项", "风险等级", "防范建议", "委托人确认", "签署栏"],
        prompt_template="请生成一份风险告知书，{law_firm}{lawyer}向委托人{client}告知{case_name}的法律风险。风险事项：{risk_items}。风险等级：{risk_level}。建议：{suggestions}。",
        law_references=["《中华人民共和国律师法》", "《律师执业行为规范》"],
    ),
    "law_case_analysis": DocTemplate(
        id="law_case_analysis",
        name="案件分析报告",
        description="案件全面分析报告。律师对案件事实、法律争议、证据、策略进行系统分析，为诉讼决策提供依据。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="分析律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人姓名/名称", required=True),
            DocTemplateField(key="case_name", label="案件名称", placeholder="如：XX诉XX合同纠纷案", required=True),
            DocTemplateField(key="case_summary", label="案情概述", placeholder="简述案件基本事实", required=True, field_type="textarea"),
            DocTemplateField(key="legal_issues", label="法律争议焦点", placeholder="列明主要法律争议点", required=True, field_type="textarea"),
            DocTemplateField(key="analysis", label="法律分析", placeholder="对争议焦点逐一分析", required=True, field_type="textarea"),
            DocTemplateField(key="evidence_analysis", label="证据分析", placeholder="现有证据的证明力分析", required=False, field_type="textarea"),
            DocTemplateField(key="strategy", label="诉讼策略建议", placeholder="如：起诉/应诉/和解等策略", required=True, field_type="textarea"),
            DocTemplateField(key="risk_assessment", label="风险评估", placeholder="胜诉可能性及风险", required=False, field_type="textarea"),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "案情概述", "法律争议焦点", "法律分析", "证据分析", "诉讼策略", "风险评估", "签署栏"],
        prompt_template="请生成一份案件分析报告，{law_firm}{lawyer}受{client}委托，分析{case_name}。案情概述：{case_summary}。争议焦点：{legal_issues}。法律分析：{analysis}。策略建议：{strategy}。",
        law_references=["《中华人民共和国律师法》"],
    ),
    "law_closing_report": DocTemplate(
        id="law_closing_report",
        name="结案报告",
        description="案件办理完毕总结报告。律师出具结案报告，总结案件结果、工作过程及后续事项。",
        category_id="lawyer_docs",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="承办律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人姓名/名称", required=True),
            DocTemplateField(key="case_name", label="案件名称", placeholder="如：XX诉XX合同纠纷案", required=True),
            DocTemplateField(key="case_no", label="案号", placeholder="如：（2025）京0105民初XXXX号", required=True),
            DocTemplateField(key="case_result", label="案件结果", placeholder="如：判决胜诉/调解结案/撤诉", required=True),
            DocTemplateField(key="result_detail", label="结果详情", placeholder="如：法院判决被告偿还本金XX元及利息", required=True, field_type="textarea"),
            DocTemplateField(key="work_summary", label="工作总结", placeholder="律师办理过程概述", required=True, field_type="textarea"),
            DocTemplateField(key="fee_settlement", label="费用结算", placeholder="如：代理费已结清", required=False),
            DocTemplateField(key="follow_up", label="后续事项", placeholder="如：如对方上诉将另行代理", required=False, field_type="textarea"),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "案件信息", "案件结果", "结果详情", "工作总结", "费用结算", "后续事项", "签署栏"],
        prompt_template="请生成一份结案报告，{law_firm}{lawyer}受{client}委托办理{case_name}（案号{case_no}）已结案。结果：{case_result}。详情：{result_detail}。工作总结：{work_summary}。",
        law_references=["《中华人民共和国律师法》"],
    ),
    "arb_apply": DocTemplate(
        id="arb_apply",
        name="仲裁申请书",
        description="商事仲裁第一步。向仲裁委员会提起仲裁申请，明确仲裁请求与事实理由。",
        category_id="arbitration",
        fields=[
            DocTemplateField(key="applicant", label="申请人", placeholder="申请人姓名/名称", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号/统一社会信用代码", placeholder="如：91110000XXXXXXXXXX", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="applicant_legal", label="法定代表人/负责人", placeholder="如：张三", required=False),
            DocTemplateField(key="respondent", label="被申请人", placeholder="被申请人姓名/名称", required=True),
            DocTemplateField(key="respondent_id", label="被申请人统一社会信用代码", placeholder="如已知请填写", required=False),
            DocTemplateField(key="respondent_address", label="被申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="arb_commission", label="仲裁委员会", placeholder="如：北京仲裁委员会", required=True),
            DocTemplateField(key="arbitration_clause", label="仲裁条款依据", placeholder="如：XX合同第X条仲裁条款", required=True),
            DocTemplateField(key="claims", label="仲裁请求", placeholder="如：1.裁决被申请人支付XX元 2.裁决被申请人承担仲裁费用", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述争议经过", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据清单", placeholder="如：1.合同 2.往来函件 3.付款凭证", required=False, field_type="textarea"),
        ],
        outline_sections=["申请人信息", "被申请人信息", "仲裁请求", "事实与理由", "证据清单", "此致仲裁委员会", "签署栏"],
        prompt_template="请生成一份仲裁申请书，申请人{applicant}，被申请人{respondent}，仲裁委员会{arb_commission}，仲裁条款依据{arbitration_clause}。仲裁请求：{claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国仲裁法》"],
    ),
    "arb_defense": DocTemplate(
        id="arb_defense",
        name="仲裁答辩书",
        description="仲裁应诉必备文书。针对仲裁申请提出答辩，逐条反驳申请人仲裁请求。",
        category_id="arbitration",
        fields=[
            DocTemplateField(key="respondent", label="答辩人（被申请人）", placeholder="答辩人名称", required=True),
            DocTemplateField(key="respondent_id", label="答辩人统一社会信用代码", placeholder="如：91110000XXXXXXXXXX", required=True),
            DocTemplateField(key="respondent_address", label="答辩人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="respondent_legal", label="法定代表人", placeholder="如：张三", required=True),
            DocTemplateField(key="applicant", label="被答辩人（申请人）", placeholder="申请人名称", required=True),
            DocTemplateField(key="arb_commission", label="仲裁委员会", placeholder="如：北京仲裁委员会", required=True),
            DocTemplateField(key="case_no", label="案号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="defense_opinion", label="答辩意见", placeholder="逐条反驳申请人的仲裁请求", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="答辩证据", placeholder="支持答辩意见的证据", required=False, field_type="textarea"),
        ],
        outline_sections=["答辩人信息", "被答辩人信息", "答辩意见", "答辩证据", "此致仲裁委员会", "签署栏"],
        prompt_template="请生成一份仲裁答辩书，答辩人{respondent}，被答辩人{applicant}，仲裁委员会{arb_commission}。答辩意见：{defense_opinion}。",
        law_references=["《中华人民共和国仲裁法》"],
    ),
    "arb_counterclaim": DocTemplate(
        id="arb_counterclaim",
        name="仲裁反请求书",
        description="仲裁反攻利器。被申请人向申请人提出仲裁反请求，变被动为主动。",
        category_id="arbitration",
        fields=[
            DocTemplateField(key="counterclaimant", label="反请求人（被申请人）", placeholder="反请求人名称", required=True),
            DocTemplateField(key="counterclaimant_id", label="反请求人统一社会信用代码", placeholder="如：91110000XXXXXXXXXX", required=True),
            DocTemplateField(key="counterclaimant_address", label="反请求人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="counterclaimant_legal", label="法定代表人", placeholder="如：张三", required=True),
            DocTemplateField(key="counterclaimed", label="被反请求人（申请人）", placeholder="被反请求人名称", required=True),
            DocTemplateField(key="arb_commission", label="仲裁委员会", placeholder="如：北京仲裁委员会", required=True),
            DocTemplateField(key="original_case_no", label="原仲裁案号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="counter_claims", label="反请求事项", placeholder="如：1.裁决被反请求人支付违约金XX元 2.驳回原仲裁请求", required=True, field_type="textarea"),
            DocTemplateField(key="facts", label="事实与理由", placeholder="详细描述反请求的事实依据", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据清单", placeholder="支持反请求的证据", required=False, field_type="textarea"),
        ],
        outline_sections=["反请求人信息", "被反请求人信息", "反请求事项", "事实与理由", "证据清单", "此致仲裁委员会", "签署栏"],
        prompt_template="请生成一份仲裁反请求书，反请求人{counterclaimant}，被反请求人{counterclaimed}，仲裁委员会{arb_commission}。反请求事项：{counter_claims}。事实与理由：{facts}。",
        law_references=["《中华人民共和国仲裁法》"],
    ),
    "arb_representation": DocTemplate(
        id="arb_representation",
        name="仲裁代理词",
        description="仲裁庭审代理意见。代理律师在仲裁庭审中发表代理意见，阐述法律观点与主张。",
        category_id="arbitration",
        fields=[
            DocTemplateField(key="law_firm", label="律师事务所", placeholder="如：XX律师事务所", required=True),
            DocTemplateField(key="lawyer", label="代理律师", placeholder="如：张XX律师", required=True),
            DocTemplateField(key="client", label="委托人", placeholder="委托人名称", required=True),
            DocTemplateField(key="client_role", label="委托人身份", placeholder="如：申请人/被申请人", required=True),
            DocTemplateField(key="opponent", label="对方当事人", placeholder="对方名称", required=True),
            DocTemplateField(key="arb_commission", label="仲裁委员会", placeholder="如：北京仲裁委员会", required=True),
            DocTemplateField(key="case_no", label="案号", placeholder="如已知请填写", required=False),
            DocTemplateField(key="case_summary", label="案情概述", placeholder="简述案件基本事实", required=True, field_type="textarea"),
            DocTemplateField(key="opinion", label="代理意见", placeholder="详细阐述代理意见和法律依据", required=True, field_type="textarea"),
            DocTemplateField(key="conclusion", label="结论", placeholder="如：请求仲裁庭支持申请人的全部仲裁请求", required=True),
        ],
        outline_sections=["律师事务所信息", "委托人信息", "案情概述", "代理意见", "结论", "签署栏"],
        prompt_template="请生成一份仲裁代理词，{law_firm}{lawyer}受{client}（{client_role}）委托，就与{opponent}的仲裁案发表代理意见。案情概述：{case_summary}。代理意见：{opinion}。结论：{conclusion}。",
        law_references=["《中华人民共和国仲裁法》"],
    ),
    "arb_cancel_apply": DocTemplate(
        id="arb_cancel_apply",
        name="撤销仲裁裁决申请书",
        description="仲裁裁决不公？申请撤销。向法院申请撤销仲裁裁决，维护自身合法权益。",
        category_id="arbitration",
        fields=[
            DocTemplateField(key="applicant", label="申请人", placeholder="申请人名称", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号/统一社会信用代码", placeholder="如：91110000XXXXXXXXXX", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="respondent", label="被申请人", placeholder="被申请人名称", required=True),
            DocTemplateField(key="respondent_address", label="被申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="管辖法院", placeholder="如：北京市第三中级人民法院", required=True),
            DocTemplateField(key="arb_commission", label="原仲裁委员会", placeholder="如：北京仲裁委员会", required=True),
            DocTemplateField(key="arb_case_no", label="仲裁案号", placeholder="如：（2025）京仲裁字第XXX号", required=True),
            DocTemplateField(key="cancel_reasons", label="申请撤销理由", placeholder="如：仲裁程序违法/裁决事项超出仲裁协议范围等", required=True, field_type="textarea"),
            DocTemplateField(key="evidence", label="证据", placeholder="支持撤销申请的证据", required=False, field_type="textarea"),
        ],
        outline_sections=["申请人信息", "被申请人信息", "仲裁裁决情况", "申请撤销理由", "证据", "此致法院", "签署栏"],
        prompt_template="请生成一份撤销仲裁裁决申请书，申请人{applicant}，被申请人{respondent}，管辖法院{court}，原仲裁委员会{arb_commission}，仲裁案号{arb_case_no}。撤销理由：{cancel_reasons}。",
        law_references=["《中华人民共和国仲裁法》第58条"],
    ),
    "arb_enforcement_apply": DocTemplate(
        id="arb_enforcement_apply",
        name="申请执行仲裁裁决书",
        description="仲裁裁决不履行？申请执行。仲裁裁决生效后向法院申请强制执行。",
        category_id="arbitration",
        fields=[
            DocTemplateField(key="applicant", label="申请执行人", placeholder="申请人名称", required=True),
            DocTemplateField(key="applicant_id", label="申请人身份证号/统一社会信用代码", placeholder="如：91110000XXXXXXXXXX", required=True),
            DocTemplateField(key="applicant_address", label="申请人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="respondent", label="被执行人", placeholder="被执行人名称", required=True),
            DocTemplateField(key="respondent_address", label="被执行人住所地", placeholder="详细地址", required=True),
            DocTemplateField(key="court", label="执行法院", placeholder="如：北京市第三中级人民法院", required=True),
            DocTemplateField(key="arb_commission", label="仲裁委员会", placeholder="如：北京仲裁委员会", required=True),
            DocTemplateField(key="arb_case_no", label="仲裁案号", placeholder="如：（2025）京仲裁字第XXX号", required=True),
            DocTemplateField(key="award_content", label="裁决内容", placeholder="简述仲裁裁决确定的内容", required=True, field_type="textarea"),
            DocTemplateField(key="execution_claims", label="申请执行事项", placeholder="如：1.强制被执行人支付XX元 2.加倍支付迟延履行期间的债务利息", required=True, field_type="textarea"),
            DocTemplateField(key="property_clue", label="财产线索", placeholder="如已知请填写", required=False, field_type="textarea"),
        ],
        outline_sections=["申请执行人信息", "被执行人信息", "仲裁裁决情况", "申请执行事项", "财产线索", "此致法院", "签署栏"],
        prompt_template="请生成一份申请执行仲裁裁决书，申请执行人{applicant}，被执行人{respondent}，执行法院{court}，仲裁案号{arb_case_no}。裁决内容：{award_content}。申请执行事项：{execution_claims}。",
        law_references=["《中华人民共和国仲裁法》第62条", "《中华人民共和国民事诉讼法》执行程序编"],
    ),
}


def get_all_doc_categories() -> List[Dict[str, Any]]:
    result = []
    for cat in DOC_CATEGORIES:
        templates_summary = []
        for tid in cat.template_ids:
            t = DOC_TEMPLATES.get(tid)
            if t:
                templates_summary.append({
                    "id": t.id,
                    "name": t.name,
                    "description": t.description,
                    "field_count": len(t.fields),
                })
        cat_dict = {
            "id": cat.id,
            "name": cat.name,
            "description": cat.description,
            "icon": cat.icon,
            "color": cat.color,
            "templates": templates_summary,
            "template_count": len(cat.template_ids),
        }
        result.append(cat_dict)
    return result


def get_doc_template_by_id(template_id: str) -> Optional[DocTemplate]:
    return DOC_TEMPLATES.get(template_id)


def search_doc_templates(keyword: str) -> List[DocTemplate]:
    keyword_lower = keyword.lower()
    results = []
    for t in DOC_TEMPLATES.values():
        if (keyword_lower in t.name.lower() or
            keyword_lower in t.description.lower() or
            keyword_lower in t.category_id.lower() or
            any(keyword_lower in f.label.lower() for f in t.fields)):
            results.append(t)
    return results


def doc_template_to_dict(t: DocTemplate) -> Dict[str, Any]:
    return {
        "id": t.id,
        "name": t.name,
        "description": t.description,
        "category_id": t.category_id,
        "fields": [
            {
                "key": f.key,
                "label": f.label,
                "field_type": f.field_type,
                "required": f.required,
                "placeholder": f.placeholder,
                "options": f.options,
                "default_value": f.default_value,
            }
            for f in t.fields
        ],
        "outline_sections": t.outline_sections,
        "prompt_template": t.prompt_template,
        "law_references": t.law_references,
    }
